### ISSUE TITLE
Laravel 5.5 ignores 'webhookUrl'

### ISSUE THREAD

**Issue by myurtsev** [mollie/laravel-mollie#100]
## Expected Behavior
function bound to webhookurl route should be triggered. I should be able to dump the request.

## Current Behavior
It redirects only to redirectUrl. Webhookurl is ignored completely.

## Steps to Reproduce (for bugs)
1.  Create payment, as shown in examples, make sure to set redirectUrl and webhookUrl ofcource, make the routes and try to dump the request.

Only redirecturl gets triggered after payment

## Context
I am trying to fetch status of payment.

## Your Environment

"laravel/framework": "5.5.39",
"mollie/laravel-mollie": "^2.0",

**Comment by sandervanhooft** [comment]
Hi @myurtsev ,

Regarding the `webhookUrl`:
- this webhook is called asynchronously , so it's possible it gets called after redirecting back to the `redirectUrl`.
- have you checked the payment in the Mollie dashboard? If you're on desktop, you can see the webhook call results on the right of the screen. What does it say?

**Comment by myurtsev** [comment]
Hi @sandervanhooft 

In Mollie staat het volgende / Webhook call results:

"Webhook met succes aangeroepen, duurde 0,5 seconden"

**Comment by sandervanhooft** [comment]
Try logging the call from the route / controller, I'm sure you should see it then in your logs.

**Comment by myurtsev** [comment]
Nevermind, it works! Thank you anyway Sander.
Turns out it was a mistake of mine I overlooked
