### ISSUE TITLE
Webhook not called

### ISSUE THREAD

**Issue by VeraGerritseDeltion** [mollie/laravel-mollie#103]
##  Expected Behavior
After payment is made, the webhook should be called to change my database.

## Current Behavior
After payment the page goes to the redirect page. But the Webhook is never called. and my database is never called

## Steps to Reproduce (for bugs)
![mollie_payment](https://user-images.githubusercontent.com/22653863/60269434-bfdbc400-98ee-11e9-88f2-95ccbc76ae23.PNG)
![mollie_handle](https://user-images.githubusercontent.com/22653863/60269436-bfdbc400-98ee-11e9-9256-457f1d642d34.PNG)
![Mollie_route](https://user-images.githubusercontent.com/22653863/60269671-35e02b00-98ef-11e9-8a07-d7f7aa11c10e.PNG)

## Your Environment
"laravel/framework": "5.8.26",
"mollie/laravel-mollie": "^2.0",

**Comment by sandervanhooft** [comment]
@VeraGerritseDeltion Can you check in the Mollie Dashboard that the webhookUrl has been set correctly, and what response Mollie gets when calling it (should be on the sidebar to the right)?

**Comment by VeraGerritseDeltion** [comment]
@sandervanhooft I can't seem to find the webhookUrl in the dashboard. in a test payment there is a redirectUrl but not a webhookUrl. Is that where you are supposed to check it? 
![Mollie_PaymentInDashboard](https://user-images.githubusercontent.com/22653863/60421838-efd6e000-9bea-11e9-8188-75bf10c57aab.PNG)

**Comment by sandervanhooft** [comment]
The `webhookUrl` doesn't seem to be sent to Mollie then. Can you check the payload?

You can use Laravel's `dd($payload)` helper method.

**Comment by petericebear** [comment]
In the handle of the webhook, do you trigger a database save? Looks like you are finding the invoice, and set the status. But no save is in the image. Could that also be a thing?

**Comment by VeraGerritseDeltion** [comment]
@sandervanhooft i tried again and the url is ther enow but it is saying that there is an error.
![image](https://user-images.githubusercontent.com/22653863/60422993-74c2f900-9bed-11e9-8f34-32f4eb377816.png)

**Comment by VeraGerritseDeltion** [comment]
@petericebear i do actualy save it. but it is indeed not in the picture

**Comment by sandervanhooft** [comment]
> i tried again and the url is there now but it is saying that there is an error.

This error means Mollie is receiving a 500 response when calling your webhook. You can probably find more in the Laravel logs.

**Comment by baristacoder** [comment]
Ah, status 500. There should be a log entry now in /storage/logs/laravel.log (default location) it could help you further.

**Comment by VeraGerritseDeltion** [comment]
it has indeed been fixed now!
thanks for all the help.
