### ISSUE TITLE
Webhook : how to catch cancelled refund ?

### ISSUE THREAD

**Issue by visualight** [mollie/laravel-mollie#104]
Hello,
I'm testing Mollie and I saw that when I cancel a refund from the dashboard, the webhook is called. I can not find any documentation to know how I can capture the canceled refund.

I need this to cancel transactions and credit notes on my server.

If I cancel a refund to the customer, the webhook displays a 500 error because it treats mollie's call as a payment and not a refund (it seems to me).

Here is a summary of the code used in the webhook. How can I capture canceled refunds?

Thank you

```
try {

            if (! $request->has('id')) {
                return;
            }
            
            $payment = Mollie::api()->payments()->get($request->id);
            
            if($payment->isPaid() && !$payment->hasRefunds() && !$payment->hasChargebacks()) {

                //Create transaction

            } elseif($payment->hasRefunds()) {

                //Create refund transaction

            } elseif($payment->hasChargebacks()) {

                //Catch user bank charge back request
            }

        } catch (ApiException $e) {
            echo "API call failed: " . htmlspecialchars($e->getMessage());
        }
```

**Comment by sandervanhooft** [comment]
Hi @visualight ,

For all refund events, the parent payment's webhook will be called. To see what happened exactly, you'll have to fetch and diff the refunds against your own records and see what has changed.

You can access the refunds using `$payment->refunds()`.

Personally, I find this a bit more complex than it should be and am discussing other solutions with Mollie, but this issue is not at the top of Mollie's backlog.

**Comment by visualight** [comment]
Hi @sandervanhooft ,

Calling  $payment->refunds() did not working.
I cannot see and get refund amount to diff with locale data.

hasRefunds method work to know if a refund has been emitted but i need to know the best method if a refund is cancelled from the mollie dashboard.

```
RefundCollection {#459 ▼
  #client: MollieApiClient {#391 ▶}
  +count: 0
  +_links: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: []
}
```

**Comment by sandervanhooft** [comment]
Ok, so the flow would be like this:

- the refund is canceled from the Mollie dashboard
- your webhook is called with the payment id (the payment for which the refund was created)
- you fetch the payment using the paymentId
- you fetch all the refunds for the payment using `$payment->refunds()`
- you check the refunds' statuses against your local refund records

On what step are you stuck currently?

**Comment by visualight** [comment]
Hi @sandervanhooft !

This is exactly what I do as a procedure except that to see what happens I fetch the payment in get mode. Note Mollie is in test mode.

1. I cancel the refund of the Mollie dashboard
2. Mollie records the cancellation but since my webhook is in get and not post, mollie puts me a 405 error (which is normal).
3. Meanwhile, I'm running my webhook manually as follows:

 ```
    try {

            /*if (! $request->has('id')) {
                return;
            }*/

            $request->id = 'tr_yjtRgT8c4k';

            $payment = Mollie::api()->payments()->get($request->id);
            if($payment->isPaid() && !$payment->hasRefunds() && !$payment->hasChargebacks()) {
                dd($payment->refunds());
            }

        } catch (\Exception $e) {
            echo "API call failed: " . htmlspecialchars($e->getMessage());
        }

// Debug show me :
RefundCollection {#459 ▼
  #client: MollieApiClient {#391 ▶}
  +count: 0
  +_links: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: []
}
```

So I do not see any clue allowing me to move forward.
An idea ?

Thank you

**Comment by sandervanhooft** [comment]
It seems to me there's an issue in your code sample:

```php
if($payment->isPaid() && !$payment->hasRefunds() && !$payment->hasChargebacks()) {
// ...
```

This means the payment is paid, has **_NO_** refunds, and has no chargebacks. A canceled refund is still a refund.

**Comment by sandervanhooft** [comment]
So it will only dump empty refund collections.

**Comment by visualight** [comment]
Hi @sandervanhooft 

If I click refund in Mollie Dashboard, I get refund with hasRefund or with $payment->refunds().

```
// Simplified webhook
try {
           $request->id = 'tr_yjtRgT8c4k'; // ID of payment where i do cancel from Mollie Dashboard
           $payment = Mollie::api()->payments()->get($request->id);
           dd($payment->refunds());

       } catch (\Exception $e) {
           echo "API call failed: " . htmlspecialchars($e->getMessage());
       }

//Mollie return : if i do a refund
RefundCollection {#463 ▼
  #client: MollieApiClient {#391 ▶}
  +count: 1
  +_links: {#473 ▼
    +"documentation": {#472 ▶}
    +"self": {#474 ▶}
    +"previous": null
    +"next": null
  }
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: array:1 [▼
    0 => Refund {#466 ▼
      +resource: "refund"
      +id: "re_WTWvujHtqH"
      +amount: {#468 ▶}
      +createdAt: "2019-07-22T07:18:16+00:00"
      +description: "Coaching vidéo"
      +paymentId: "tr_yjtRgT8c4k"
      +orderId: null
      +lines: null
      +settlementAmount: {#464 ▶}
      +status: "pending"
      +_links: {#461 ▶}
      #client: MollieApiClient {#391 ▶}
      +"metadata": null
    }
  ]
}

// Mollie return : if I cancel a refund from dashboard
RefundCollection {#459 ▼
  #client: MollieApiClient {#391 ▶}
  +count: 0
  +_links: null
  flag::STD_PROP_LIST: false
  flag::ARRAY_AS_PROPS: false
  iteratorClass: "ArrayIterator"
  storage: []
}
```
When i do a cancel refund, $payment->refunds() is empty.
So why Mollie Call the Webhook when we cancel refund if we cannot catch the cancel and make appropriate work server side ?

We need to catch an action like : hasRefundChargeBack or something else to have the canceled refund collection and update our DB.

I attempt to contact Mollie since 2 week (email, phone) ... without success.

**Comment by sandervanhooft** [comment]
Ah, ok, now I understand. Thanks for clearing that up.

I think that diffing the refundCollection would still be the best solution here. So if the refund no longer exists, assume it was canceled.

One other thing you could try is fetching the payment [using the embed refunds parameter](https://docs.mollie.com/reference/v2/payments-api/get-payment#parameters). Perhaps this will include canceled refunds as well.

**Comment by visualight** [comment]
Thank you @sandervanhooft 

Last thing : how i can pass the "embed" query string with the Mollie laravel API ?
`$payment = Mollie::api()->payments()->get($request->id);`

Have a nice day.

**Comment by sandervanhooft** [comment]
No problem!

Should be something like:

```php
$payment = $payment = Mollie::api()->payments()->get($request->id, ['embed' => 'refunds']);
```

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it needs to be reopened.
