### ISSUE TITLE
array_add error when upgrading to Laravel 6.x 

### ISSUE THREAD

**Issue by Dennisprins93** [mollie/laravel-mollie#110]
When I try to connect via oauth with mollie connect I get that the array_add method is undefined. 

There is a function `getTokenFields` in `MollieConnectProvider.php` around line 149. This is calling a helper called `array_add`. This was a helper that was present in 5.8, but is now removed in 6.x and now has to be:

```
use Illuminate\Support\Arr;
...
Arr:add();
```

Compare these files from the laravel framework and you'll see that it's removed:

Laravel 5.8:
https://github.com/laravel/framework/blob/5.8/src/Illuminate/Support/helpers.php` on line `38`

Laravel 6.x:
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Support/helpers.php

Quick fix for the time being can be to copy/paste the old global helper and put it in your local helper file in your `App` directory. 

```
if (! function_exists('array_add')) {
    /**
     * Add an element to an array using "dot" notation if it doesn't exist.
     *
     * @param  array   $array
     * @param  string  $key
     * @param  mixed   $value
     * @return array
     *
     * @deprecated Arr::add() should be used directly instead. Will be removed in Laravel 6.0.
     */
    function array_add($array, $key, $value)
    {
        return Arr::add($array, $key, $value);
    }
}
```

Can this be fixed in a next release?

**Comment by sandervanhooft** [comment]
Hi @Dennisprins93 ,

That's correct. Could you prepare a PR with the _full_ old function? (So not using `Arr::add(...)`)?

**Comment by Dennisprins93** [comment]
I don’t get it. The old function is array_add, but that can’t be used anymore. But the old “array_add” in laravel/framework 5.8 was returning “Arr::add”. So what exactly do you expect in the PR?

**Comment by sandervanhooft** [comment]
Taking a different approach, preparing a PR here: #111, releasing today.
