### ISSUE TITLE
Payment status Test mode

### ISSUE THREAD

**Issue by remcomulders** [mollie/laravel-mollie#113]
Hi guys,

While testing the Mollie API, I get redirected to the Mollie Checkout screen (as expected). However, if I check the payment status anything else as Paid, I get redirected back to chose a payment method. Only if I check Paid or if I press "Previous Website" in the bottom left corner, I get forwarded to my success or canceled page, respectively. Is this the way it should be? Or should I always be forwarded when I choose a payment status? 
My webhook is working since the status changes are being transmitted to my database. 

Thanks in advance!

**Comment by sandervanhooft** [comment]
Hi @remcomulders ,

Seems like there's a loop. Can you check whether the url you're using for the `redirectUrl` is sending the customer to Mollie's checkout (because it shouldn't)?

**Comment by sandervanhooft** [comment]
Scratch that. Just checked with support. It's normal behaviour.

**Comment by sandervanhooft** [comment]
From support:

> This is normal.
When a payment can be paid with more than one method the consumer goes back to the method selection screen after a failed / cancelled payment.
The consumer can select an other payment method to complete the payment with.
There is a "abandon payment" link in the bottom left of the payment selection screen.

**Comment by remcomulders** [comment]
Awesome, thanks for checking. Seems like everything works fine than! Again, thank you! Amazing API, keep it up!

**Comment by zynth666** [comment]
Wait, how are you supposed to test different status on your order? And what's the point of choosing a status if it never reaches your redirect? This should work differently in test mode, shouldn't it?

**Comment by sandervanhooft** [comment]
Hi @zynth666 ,

👉  This is off-topic and also a very old closed issue ticked. For any follow-up please open a new Issue ticket or post your question in the [Mollie Discord](https://discord.gg/mollie).

> Wait, how are you supposed to test different status on your order?

By setting the status on the test payment related to that order using the `changePaymentState` link available on the API Payment resource [docs](https://docs.mollie.com/overview/testing).

> And what's the point of choosing a status if it never reaches your redirect?

For orders created with an existing payment mandate the customers do not go through the hosted checkout. For these cases it still makes sense for the status to be changeable in order for the integration to be testable.

> This should work differently in test mode, shouldn't it?

Yes, the `changePaymentState` link is only available in test mode.
