### ISSUE TITLE
"No suitable payment methods found" for SEPA payement

### ISSUE THREAD

**Issue by sylvainR37** [mollie/laravel-mollie#115]
I want to set up a payment recur with the SEPA method but I can not be redirected to the form.

`$customer = Mollie::api()->customers()->create([
            "name"  => "John Doe",
            "email" => "john@doe.com",
        ]);

        $payment = Mollie::api()->payments()->create([
            "amount" => [
                "currency" => "EUR",
                "value"    => "25.00", // You must send the correct number of decimals, thus we enforce the use of strings
            ],
            "customerId"   => $customer->id,
            "sequenceType" => "first",
            "description"  => "My Initial Payment",
            "redirectUrl"  => route("home"),
            "webhookUrl"   => route("webhooks.mollie"),
        ]);

        // Redirect the user to Mollie"s payment screen.
        redirect($payment->getCheckoutUrl(), 303);`
error : 

> No suitable payment methods found.

**Comment by sandervanhooft** [comment]
For future reference: this error occurs when there are no (suitable) payment methods enabled on the profile. Check the Mollie dashboard.
