### ISSUE TITLE
Difference between MOLLIE_KEY and MOLLIE_SECRET

### ISSUE THREAD

**Issue by PMBergman** [mollie/laravel-mollie#12]
Hi,

I just added the mollie larval wrapper to my project. The config file states the following:
// Place the following in the 'config/services.php'
    // 'mollie' => [
    //     'client_id'     => env('MOLLIE_KEY'),
    //     'client_secret' => env('MOLLIE_SECRET'),
    //     'redirect'      => env('MOLLIE_REDIRECT_URI'),
    // ],

What is the difference and which values do I need to use?

**Comment by FaaPz** [comment]
Hi @PMBergman, we've updated the config file (81415e598e30947cbc2e010dda9f3814b87c553a) to be more understandable. You only have to copy/paste this code snippet in `config/services.php` if you're going to use [Mollie Connect](https://www.mollie.com/en/docs/oauth/overview).

The `MOLLIE_KEY` is now called `MOLLIE_CLIENT_ID` and should contain your unique give application ID located in [Mollie Dashboard](https://www.mollie.com/dashboard/applications). `MOLLIE_SECRET` is renamed to `MOLLIE_CLIENT_SECRET` and should contain the associated application secret.

If you're not intending to develop an application with Mollie Connect, you can leave it commented out.
