### ISSUE TITLE
Apple pay integration

### ISSUE THREAD

**Issue by fvanhove** [mollie/laravel-mollie#120]
How is the Apple pay integration intended to be used? 
It seems after enabling this in the Mollie payment methods it is still not provided in the response of 
`mollie()->methods()->all()`

Does this only work for the Mollie checkout flow or can the Apple pay direct integration be used? 
if so, how would this be used together with the laravel-mollie package? 

Kind regrads

**Comment by sandervanhooft** [comment]
Hi @fvanhove,

**About `Laravel-mollie` vs `mollie-api-php`**

This Laravel package builds upon the `mollie-api-php` client. The primary benefit of the Laravel package is that it preconfigures the php client using Laravel best practices.

The `laravel-mollie` endpoint methods are therefore similar to the `mollie-api-php` endpoint methods.

So if in the [mollie docs](https://docs.mollie.com/reference/v2/) you see an example like this:

```php
$mollie->payments->get($id);
```

that would be this in the `laravel-mollie` client:
```
mollie()->payments()->get($id);
```

**How to integrate Apple Pay**
Best to use these docs:

- Mollie guides: [Apple Pay](https://docs.mollie.com/wallets/applepay) and [Direct integration of Apple Pay](https://docs.mollie.com/guides/applepay-direct-integration)
- Mollie API reference: [Requesting Apple Pay Payment Session](https://docs.mollie.com/reference/v2/wallets-api/request-apple-pay-payment-session
)

➡️ I'm checking your specific question about the method endpoint with Mollie.

**Comment by sandervanhooft** [comment]
Hi @fvanhove ,

Can you try the following?

```php
mollie()->methods()->all(["includeWallets=applepay"])
```

**Comment by fvanhove** [comment]
Hey, @sandervanhooft. 

I think you meant: 
`mollie()->methods()->all(["includeWallets" => "applepay"]);

That indeed adds the apple pay method to the list, thanks for the info.

**Comment by sandervanhooft** [comment]
You're right! Glad it helped.
