### ISSUE TITLE
cURL error 2

### ISSUE THREAD

**Issue by mehedi-iitdu** [mollie/laravel-mollie#123]
Mollie\Api\Exceptions\ApiException
cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by sandervanhooft** [comment]
Hi,

Can you provide information about the versions you’re using for:

- laravel mollie
- guzzle
- php

**Comment by mehedi-iitdu** [comment]
"php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "mollie/laravel-mollie": "^2.0",

**Comment by sandervanhooft** [comment]
Could you use

`composer show <dependency name>`

for each package to obtain the actual versions in use?

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
