### ISSUE TITLE
PaymentID undefined variable

### ISSUE THREAD

**Issue by flowroma** [mollie/laravel-mollie#124]
I have two issues which I had not experienced without the laravel framework. So when I require the package in composer, I get both mollie-laravel and mollie-php and I am using the latest version of the package.

I face two issues:

1. Setting up my api key in .env file is not recognized. I have to manually enter this in vendor/mollie/mollie-api-php/src/MollieApiClient.php and some other places in the mollie-laravel files. What would cause the key in the .env file not to be recognized?

2. I have an issue with checking if a payment has been made. I have set this to `route ('thankyou'). `
The route is set up as
`Route::get('thankyou', 'FrontController@thankyou')->name('thankyou');`
And this is the FrontController:
```
public function thankyou () {

        $payment = Mollie::api()->payments()->get($payment->id);

        if ($payment->isPaid()) {
            return view ('cart')->with('succes_message','Bedankt, jouw bestelling is succesvol gedaan, hieronder zie je een overzicht van je bestelling');
        }

        else {
            return view ('cart')->with('info_message','Er is iets mis gegaan bij je bestelling');
        }

    }
```
Now the point is to check whether a payment has been made and return the view to the cart with a message. In any other case (cancellation, expiration of payment, failed payment) an error is shown.
In my case, the thank you page shows the following error upon cancellation of a payment:
` Invalid payment ID: ''. A payment ID should start with 'tr_'. `

Now you could argue to use the webhook for what I want to do. I have the same logic there (if payment success, return view to cart with a message and if payment fails, return to view with error) but that isn't working either. I think it has to do with the payment ID.

I am using my live key in testing. Thanks for the help.

**Comment by sandervanhooft** [comment]
1. Try clearing the config cache. If that doesn’t work, check if this package’s ServiceProvider is registered.

2. Where’s the `id` in your `$request` coming from?

**Comment by flowroma** [comment]
1. First deleting the config cache and registering the ServiceProvider (which wasn't registered for some reason) gives the follow error:


Fatal error: Uncaught Error: Call to undefined method Illuminate\Foundation\Application::withFacades() in /home/***/***.nl/bootstrap/app.php:29 Stack trace: #0 /home/***/***.nl/public/index.php(40): require_once() #1 {main} thrown in /home/***/***.nl/bootstrap/app.php on line 29

This is line 29: `$app->withFacades(true, ['Mollie\Laravel\Facades\Mollie' => 'Mollie']);`

2. That is supposed to come from `$payment = Mollie::api()->payments()->create([]);` since it needs to be a payment id generated by Mollie starting with tr_

**Comment by flowroma** [comment]
I will do a fresh install first. Something's messed up with composer and how I installed the Mollie package

**Comment by flowroma** [comment]
Now that issue 1 is resolved by a fresh install, let's focus on issue 2.

In the PreparePayment function, after the creation of a payment, a payment id is created and available in the $payment->id property.  I removed the Request now since a payment id is automatically created and stored in the payment id property.

In the thank you function, where I try to retrieve the payment id, the return is the error: invalid payment ID, a payment should start with tr_.

**Comment by sandervanhooft** [comment]
I’m not sure where you’re getting the id from, usually you get it from the webhook, not in the redirect. Can you share an example id string?

**Comment by flowroma** [comment]
Aha yes I understand now. One gets the id from the webhook, stores it in the database and then retrieves it to show on a thank you page. Except when I look at my payments dashboard, the webhook cannot be called. 
`
> Aanroepen webhook mislukt (Got HTTP/1.1 500 Internal Server Error instead of 20x)`

I have set up everything exactly as https://github.com/mollie/laravel-mollie/blob/master/docs/webhook.md

So I guess my main problem now is the webhook now

**Comment by flowroma** [comment]
I will create a new issue as the current problem is not representative of the initial problem
