### ISSUE TITLE
Webhook 500 internal error

### ISSUE THREAD

**Issue by flowroma** [mollie/laravel-mollie#125]
I am getting the following message in Mollie Dashboard: 
`Aanroepen webhook mislukt (Got HTTP/1.1 500 Internal Server Error instead of 20x)`

I have set up the webhook exactly as https://github.com/mollie/laravel-mollie/blob/master/docs/webhook.md

The laravel error log shows

`local.ERROR: Undefined variable: payment {"exception":"[object] (ErrorException(code: 0): Undefined variable: payment at /home/***/***.nl/app/Http/Controllers/MollieWebhookController.php:15)`

Why is the variable payment undefined? Isn't this supposed to be generated by Mollie itself?

**Comment by Jubeki** [comment]
Could you send the code for the MollieWebhookController?

**Comment by flowroma** [comment]
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mollie\Laravel\Facades\Mollie;

class MollieWebhookController extends Controller
{
    public function handle(Request $request) {
        if (! $request->has('id')) {
            return;
        }

        $payment = Mollie::api()->payments()->get($payment->id);

        if ($payment->isPaid()) {
            return view ('cart')->with('succes_message','Bedankt, jouw bestelling is succesvol gedaan en je krijgt een e-mail voor de bevestiging');
        }

    }
}

```

**Comment by sandervanhooft** [comment]
```php
$payment = Mollie::api()->payments()->get($payment->id);
```

should be

```php
$payment = Mollie::api()->payments()->get($request->get('id'));
```

**Comment by sandervanhooft** [comment]
Note that the error message was actually helpful here 😄 .

**Comment by flowroma** [comment]
Damn, I thought I had copy pasted everything exactly. Stupid :( 
Thanks Sander, that solved the problem!
