### ISSUE TITLE
 Error executing API call (request): Unknown field: currency.

### ISSUE THREAD

**Issue by vdvcoder** [mollie/laravel-mollie#127]
When i try local it works. and i see the mollie payment page.
When i try it online it doesn't go to the mollie page but give this error:

**Error executing API call (request): Unknown field: currency.**

**Comment by Jubeki** [comment]
Could you provide a code example of what you are doing?

**Comment by vdvcoder** [comment]
try {
            //Here we will do the mollie payment.
            $payment = Mollie::api()->payments()->create([
                'amount' => [
                    'currency' => "EUR",
                    'value' => (string) number_format($total, 2, '.', ' '), // You must send the correct number of decimals, thus we enforce the use of strings
                ],
                'description' => "Order #" . $orderId . "Uw bestelling voor afhaling bij Gusteaux",
                'webhookUrl' => route('webhooks.mollie'),
                'redirectUrl' => route('order.success'),
                'metadata' => [
                    "orderId" => $orderId,
                    "customer" => $naamCustomer,
                    "email" => $emailCustomer,
                    "phone" => $phoneCustomer
                ],
            ]);

        } catch (\Throwable $th) {
            return redirect()->route('checkout')->with('error', $th->getMessage());
        }
        

        $order = new MeatOrder();
        $order->orderId = $orderId;
        $order->cart = serialize($cart);
        $order->payment_status = $payment->status;
        $order->name = $naamCustomer;        
        $order->email = $emailCustomer;
        $order->address = $addressCustomer;
        $order->postcode = $postcodeCustomer;
        $order->gemeente = $gemeenteCustomer;
        $order->phone = $phoneCustomer;

        $order->save();

        $payment = Mollie::api()->payments()->get($payment->id);

        Session::forget('cart');

        
        // redirect customer to Mollie checkout page
        return redirect($payment->getCheckoutUrl(), 303);

**Comment by Jubeki** [comment]
I don't see anything wrong even after testing for a bit.

What you could check for now would be the following:
- Which status code is returned by mollie (better would be the whole response)?
- Is the code on the server the same as the local one?

Also, could you provide information about your current environment:
- laravel
- laravel mollie
- guzzle
- php
