### ISSUE TITLE
Redirect canceled payment to different redirectUrl

### ISSUE THREAD

**Issue by timwass** [mollie/laravel-mollie#128]
Hi, I have worked with other payment providers and often there is a status parameter added to the redirectUrl so I immediately can see if I have to display a success or canceled page after the payment.

With Mollie this seems not the case, it just redirects to the redirectUrl without any additional parameters. I have tried to add the order id to the redirectUrl and check the payment status of the order on return but this doesn't work reliable. Sometimes the webhook is called before and sometimes it is called after the redirectUrl. 

I'm probably just overlooking something but how can I redirect the user to a canceled page if they cancel the payment?

**Comment by sandervanhooft** [comment]
I've solved this in Spark for Mollie by - before redirecting the customer to Mollie - adding the `paymentId` to the payment's `redirectUrl`. Then I use a `RedirectFromMollieController` to check the payment's `status` using that id, and redirect to the right screen (or flash the right message).

Mollie will always call the webhook before redirecting.

Does that help?

**Comment by timwass** [comment]
Adding the paymentId to the redirectUrl before redirecting the user works great, now I can check the payment status when the customer returns to the website and redirect to the right page. Thanks for the help!

**Comment by zerdotre** [comment]
@sandervanhooft I dont think thats true. I have had trouble displaying the payment result at redirect. I've also logged the results, and the redirect gets called before the webhook. So I couldnt rely on webhook getting called being true. 

Another dubiety:
You also dont know how long the webhook takes to load.

**Comment by sandervanhooft** [comment]
@zerdotre , correct, this behaviour has slightly changed on since my original post in 2020.

**Comment by zerdotre** [comment]
@sandervanhooft Ok, thanks for the clarification. Can I ask what would be
your solution to the problem that when a customer is redirected to the
redirectUrl, this page shows the paymentStatus as pending? The webHook
delay is max a little over 1000ms as per my tests.
I thought of:
- sleep(1sec), or
- ajax checking every 100ms orso and then updating the page.

Both are not really nice solutions imo.

**Comment by sandervanhooft** [comment]
The methods you suggested are the most common way to handle this.

**Comment by zerdotre** [comment]
Especially since its a direct/immediate payment. With a method like bank
transfer this behaviour is expected, but jot with cc/iDeal/etc.
