### ISSUE TITLE
Some typos in README.md

### ISSUE THREAD

**Issue by webinn** [mollie/laravel-mollie#130]
In the snippet under https://github.com/mollie/laravel-mollie#a-payment-using-the-mollie-api
we see some typo's: 

$payment = Mollie::api()->payments->create([[  (double bracket instead of single)
redirectUrl and webhookUrl have switched routes

Just minor things :)

**Comment by sandervanhooft** [comment]
I don't see them, but feel free to send in a PR :).

**Comment by webinn** [comment]
somebody already fixed them, but no worries ;) thanks for your work!
