### ISSUE TITLE
Undefined property: Mollie\Laravel\Wrappers\MollieApiWrapper::$payments

### ISSUE THREAD

**Issue by priya1890** [mollie/laravel-mollie#132]
I am using the Mollie Laravel package and followed the instructions as in readme, but getting the error,

Undefined property: Mollie\Laravel\Wrappers\MollieApiWrapper::$payments

$createPayment =  mollie()->payments->create([
                    "amount" => [
                        "currency" => $currency,
                        "value" => (string)$price // You must send the correct number of decimals, thus we enforce the use of strings
                    ],
                    "description" => $description,
                    "redirectUrl" => $websiteReturnURL,
                    "webhookUrl" => $webhookURL,
                    "metadata" => [
                        "order_id" => $transactionID,
                    ],
                ]);

also tried with facades as ,
\Mollie\Laravel\Facades\Mollie::api()->payments
Mollie::api()->payments

**Comment by sandervanhooft** [comment]
https://github.com/mollie/laravel-mollie/releases/tag/v2.10.0

**Comment by priya1890** [comment]
@sandervanhooft thank you for your response. I am using Laravel version 5.5, so the release version v2.10.0 is not compatible to the laravel version am using. Can u help with this?

**Comment by sandervanhooft** [comment]
You can either upgrade to a newer Laravel version, or use this instead:


`$createPayment = mollie()->payments()->create(/*...*/);`

Note the added `()` behind `payments`.

**Comment by priya1890** [comment]
@sandervanhooft Thank you so much, $createPayment = mollie()->payments()->create(/*...*/); worked for me.

**Comment by sandervanhooft** [comment]
Enjoy!
