### ISSUE TITLE
Disable refund option from User

### ISSUE THREAD

**Issue by rashidabbas7865** [mollie/laravel-mollie#133]
When I redirected to `redirectUrl` and after that I hit back button from browser, It enables the user to request for refund. Is there any way to disable this feature stop redirecting back to previous page.

**Comment by sandervanhooft** [comment]
Hi,

I believe this only happens in test mode right?

**Comment by rashidabbas7865** [comment]
Yes, I'm using testmode, but not sure if same thing will happen in prod?

**Comment by sandervanhooft** [comment]
AFAIK this is only in test mode. If you want to do a refund in production, you can do so in the Dashboard or using the API. Not via this route, that’s only a testing convenience.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by rashidabbas7865** [comment]
You can close this case. Thanks for help. I have new concern going to open new case.
