### ISSUE TITLE
Failed payment redirect

### ISSUE THREAD

**Issue by rashidabbas7865** [mollie/laravel-mollie#134]
I'm using testmode and when I make a successful payment it redirects me to `redirectUrl` But when I choose a failed payment, it keeps me in loop to choose to payment option and doesn't redirect me to some custom page. I want to redirect user to a page on failed payment.  Is there a way to do this?

Thank you

**Comment by JorikMollie** [comment]
Hi @rashidabbas7865,

This is not something that this integration does, but behaviour of the Mollie platform.

When you create a payment / order without a "method" parameter your customer is redirected to the method selection screen on the Mollie platform. To improve conversion, your customer can retry the payment if an attempt fails. So after a failed payment the customer is redirected to the method selection screen.

You can cancel the payment via the "back"-link on the bottom of the payment selection screen.

**Comment by rashidabbas7865** [comment]
So you mean if I fix the payment method inside the request. Then it will not redirect to the payment method selection again?

Actually I want to redirect him to some custom url when the payment is failed.

**Comment by sandervanhooft** [comment]
@rashidabbas7865 may be this is helpful to you: https://github.com/mollie/laravel-mollie/issues/128 .

**Comment by rashidabbas7865** [comment]
@sandervanhooft Thanks for the help. I will pass the payment id after creating request.

I have another questions. 


as it calls webhook before `redirectUrl` so If I validate payments only in webhook is that correct and secure? I dont want to validate payments on `redirectUrl `  to make changes in db. ofcourse i have to validate for failed and paid etc. but I dont want to change database on this page. because user will have free hand on this page.

**Comment by sandervanhooft** [comment]
Correct, the webhook is the trigger to listen for in order to update the payment state in your application. The webhook is called before the customer is redirected back to your application.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.

**Comment by rashidabbas7865** [comment]
Sure Thanks.
