### ISSUE TITLE
How to update a payment?

### ISSUE THREAD

**Issue by ToonDG** [mollie/laravel-mollie#135]
According to the API docs, payments can be updated: [https://docs.mollie.com/reference/v2/payments-api/update-payment](https://docs.mollie.com/reference/v2/payments-api/update-payment)

I can't however, find out how to do it using this library.

- There is no update function in PaymentEndpoint.
- The EndpointAbstract has a REST_UPDATE constant, but no function that uses it.

Is is possible to update a payment using this library?

**Comment by sandervanhooft** [comment]
You may be overthinking it 😉 

https://docs.mollie.com/reference/v2/payments-api/update-payment#example

Closing this for now, let me know if it should be reopened.

**Comment by ToonDG** [comment]
Thank you. I didn't see the php example in the docs.

`$payment->update();` did the trick.

**Comment by sandervanhooft** [comment]
No problem, enjoy! 🕺
