### ISSUE TITLE
Auth::guest not working in webhook

### ISSUE THREAD

**Issue by flowroma** [mollie/laravel-mollie#136]
Hi,

I want to check that if a user books as a guest, they get a welcome email. If they are logged in, they don't get the welcome email.
So in the webhook I have the following code:

```
if ($payment->isPaid()) {
 if (Auth::guest()) {
                $order = Order::with('products')->where('mollie_id', '=', $payment->metadata->order_id)->firstOrFail();
                Mail::send (new NewAccount ($order));
            }
}
```
The problem is that the welcome email gets sent, even if a user is logged in. It seems the Auth::guest check gets bypassed. What am I overlooking? 

(Of course, there are alternatives, but I'd like to know why this isn't working)

**Comment by Jubeki** [comment]
`Auth::guest()` is working as intended. The webhook is called from mollies servers, so it will always be unauthenticated in your laravel application.

You could determine the user/guest from the order which you have saved.

**Comment by flowroma** [comment]
Aha yes of course, that makes sense. Thanks. I can't determine the user/guest from the order, because both are getting an account, so I'll do it before they are redirected to the confirmation page.
