### ISSUE TITLE
openssl error

### ISSUE THREAD

**Issue by ruteeb** [mollie/laravel-mollie#137]
when I open my website asp-school.nl,  the website gave me the following error message:
Unable to communicate with Mollie (35): OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.mollie.nl:443 . (View: C:\inetpub\vhosts\asp-school.nl\laravel\resources\views\master2.blade.php) (View: C:\inetpub\vhosts\asp-school.nl\laravel\resources\views\master2.blade.php)

## Expected Behavior
- sometimes the error appears when I open a normal page, there is no need to pay via mollie to get this error message 
- the error not always appears.
- this error appears since 2 weeks

## Steps to Reproduce (for bugs)

1.I check SSL certificate and it works fine
2.
3.
4.

## Context

just open the website

## Your Environment

* Version used: laravel 5.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): laravvel 5.2
* Operating System and version (desktop or mobile): all versions 
* Link to your project: asp-school.nl

**Comment by ruteeb** [comment]
if you attempt to refresh the page the website continues normally.
sometimes the error not appear at all for a couple of hours

**Comment by sandervanhooft** [comment]
What laravel-mollie version are you using?

`composer show mollie/laravel-mollie`

**Comment by ruteeb** [comment]
where can I find it, please?

**Comment by sandervanhooft** [comment]
By running

`composer show mollie/laravel-mollie`

**Comment by ruteeb** [comment]
name     : mollie/laravel-mollie
descrip. : Mollie API client wrapper for Laravel & Mollie Connect provider for Laravel Socialite
keywords : api, bancontact, banktransfer, belfius, belfius direct net, bitcoin, charges, creditcard, direct debit, gateway, ideal, laravel, lumen, mistercash, mollie, payment, payments, paypal,
paysafecard, podiumcadeaukaart, recurring, refunds, sepa, service, socialite, sofort, sofortbanking, subscriptions
versions : * v1.5.1
type     : library
license  : BSD 2-Clause "Simplified" License (BSD-2-Clause) (OSI approved) https://spdx.org/licenses/BSD-2-Clause.html#licenseText
homepage : https://github.com/mollie/laravel-mollie
source   : [git] https://github.com/mollie/laravel-mollie.git b49e597c5552e7ff36ae97a85a5a1c55f3bc6e07
dist     : [zip] https://api.github.com/repos/mollie/laravel-mollie/zipball/b49e597c5552e7ff36ae97a85a5a1c55f3bc6e07 b49e597c5552e7ff36ae97a85a5a1c55f3bc6e07
path     : C:\inetpub\vhosts\asp-school.nl\laravel\vendor\mollie\laravel-mollie
names    : mollie/laravel-mollie

autoload
psr-4
Mollie\Laravel\ => src/

requires
illuminate/contracts ^5.0
illuminate/support ^5.0
mollie/mollie-api-php ^1.9
php ^5.5.9 || ^7.0

requires (dev)
graham-campbell/testbench ^3.1
mockery/mockery ^0.9.5
phpunit/phpunit ^4.8 || ^5.0

suggests
laravel/socialite Use Mollie Connect (OAuth) to authenticate via Laravel Socialite with the Mollie API. This is needed for some endpoints.

**Comment by sandervanhooft** [comment]
There has been no update to this version (v1.5.1). Did you update any of the dependencies?

**Comment by ruteeb** [comment]
No

**Comment by sandervanhooft** [comment]
I'll check with Mollie support if this is a known issue (the open SSL message).

Meanwhile, I've checked both `mollie/laravel-mollie` and the underlying `mollie/mollie-api-php` packages, they're not initiating any calls on their own. Can you please check what is triggering these calls?

**Comment by ruteeb** [comment]
If I buy from mollie it is normal. Did you mean that?

**Comment by sandervanhooft** [comment]
I meant this:

@ruteeb [wrote](https://github.com/mollie/laravel-mollie/issues/137#issue-654144045):
> sometimes the error appears when I open a normal page, there is no need to pay via mollie to get this error message

The package will not call Mollie's API without being triggered by your app. So make sure you know what is triggering these calls when you're not preparing a payment.

Also, for security reasons, consider updating your Laravel installation. Laravel v5.2 went out of security support [a long time  ago](https://laravel.com/docs/6.x/releases#support-policy).

**Comment by ruteeb** [comment]
there is no trigger when I open home page for example 
so I am really confused about that

**Comment by ruteeb** [comment]
I hope that you can help me in that

**Comment by sandervanhooft** [comment]
The 35 OPEN SSL error is usually caused by an outdated cURL installation. Can you update cURL?

**Comment by ruteeb** [comment]
I did not understand you totally, would you please give me a reference how to update curl?

**Comment by ruteeb** [comment]
I did search using google but i did not find how to update it

**Comment by ruteeb** [comment]
yes thank you I have a solution

**Comment by sandervanhooft** [comment]
Great, enjoy!
