### ISSUE TITLE
The webhook URL is invalid because it is unreachable from Mollie's point of view

### ISSUE THREAD

**Issue by gabzon** [mollie/laravel-mollie#138]
Hello, 

I was testing Mollie in local. I was following the given example, but when I try to call mollie using the webhookUrl, I get this error:

Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view

Do I need to configure a local point for testing in Mollies Dashboard? Any ideas?
Thanks

**Comment by sandervanhooft** [comment]
Use ngrok or expose

**Comment by gabzon** [comment]
You mean this [expose](https://beyondco.de/docs/expose/introduction) ?

https://dancefloor.sharedwithexpose.com

**Comment by sandervanhooft** [comment]
> You mean this [expose](https://beyondco.de/docs/expose/introduction) ?
> 
> https://dancefloor.sharedwithexpose.com

Yes. You'll need to [enable SSL](https://beyondco.de/docs/expose/server/ssl).

If you have a working `valet` installation, that could be simpler. I.e.

```
valet link
valet secure
valet share
```

**Comment by gabzon** [comment]
Ok I followed your instructions (never done this before)

I ran valet link, secure, and share

I got this on the terminal

`ngrok by @inconshreveable                                                                                                                                                       (Ctrl+C to quit)
                                                                                                                                                                                                
Session Status                online                                                                                                                                                            
Session Expires               7 hours, 54 minutes                                                                                                                                               
Version                       2.3.35                                                                                                                                                            
Region                        United States (us)                                                                                                                                                
Web Interface                 http://127.0.0.1:4040                                                                                                                                             
Forwarding                    http://0b170acd6cf2.ngrok.io -> http://dancefloor.test:60                                                                                                         
Forwarding                    https://0b170acd6cf2.ngrok.io -> http://dancefloor.test:60                                                                                                        
                                                                                                                                                                                                
Connections                   ttl     opn     rt1     rt5     p50     p90                                                                                                                       
                              11      1       0.02    0.02    65.09   67.02                                                                                                                     
                                                                                                                                                                                                
HTTP Requests                                                                                                                                                                                   
-------------                                                                                                                                                                                   
                                                                                                                                                                                                
GET /courses/1                 200 OK                                                                                                                                                           
GET /                          302 Found                                                                                                                                                        
GET /favicon.ico               404 Not Found                                                                                                                                                    
GET /images/salsa-fusion.png   200 OK                                                                                                                                                           
GET /css/app.css               200 OK                                                                                                                                                           
GET /livewire/livewire.js      200 OK                                                                                                                                                           
GET /courses/1                 200 OK                                                                                                                                                           
GET /                          302 Found                                                                                                                                                        
GET /courses/1                 200 OK                                                                                                                                                           
GET /                          302 Found   `

And I reopen again expose, just in case

**Comment by sandervanhooft** [comment]
Use either `valet` or `expose`, not both.

When using `valet`, make sure to set the `ngrok` provided url in your `.env`.

**Comment by gabzon** [comment]
Ok! 

First of all, thank you for your patience. 

`So I ran again valet share --region=eu`

and I added this to the .env
```
NGROK_HTTP=http://40924a7b19f5.ngrok.io
NGROK_HTTPS=https://40924a7b19f5.ngrok.io
```
is this correct?

**Comment by sandervanhooft** [comment]
Oh sorry, I meant `APP_URL=https://your-ngrok-url-here.io`

**Comment by gabzon** [comment]
Done

https://2dcde7ca4a21.eu.ngrok.io

Actually every time I'm exiting and running again valet share, I don't dont know if it is necessary or if it is done realtime

**Comment by sandervanhooft** [comment]
You can leave it open (otherwise you'll need to update your `.env` every time, valet generates a new url on each start)

**Comment by sandervanhooft** [comment]
Mollie should be able to reach your webhook now.

**Comment by gabzon** [comment]
Still nothing :( I'm getting 

```
Mollie\Api\Exceptions\ApiException
Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/guides/handling-errors
https://dancefloor.test/mollie-payment?amount=40
```

Maybe I did something wrong have someI have this:

```
class MollieWebhookController extends Controller
{
    public function handle(Request $request) {
        
        if (! $request->has('id')) {
            return;
        }

        $payment = Mollie::api()->payments()->get($request->id);

        if ($payment->isPaid()) {
            return view('payments.status');
            //auth()->user()->setRegistrationStatus()
            //$course->students()->attach(auth()->user()->id, ['role'=>'student', 'status'=>'pending', 'created_at'=> now()]);
        }
    }
}
```
and another class

```
class MollieController extends Controller
{
    public function  __construct()
    {
        $mollieKey = config('services.mollie.key');
        Mollie::api()->setApiKey($mollieKey); // your mollie test api key
    }

    /**
     * Redirect the user to the Payment Gateway.
     *
     * @return Response
     */
    public function preparePayment()
    {
        $payment = Mollie::api()->payments()->create([
            'amount'        => [
                'currency'      => 'EUR', // Type of currency you want to send
                'value'         => request()->amount . '.00', // You must send the correct number of decimals, thus we enforce the use of strings
            ],
            'description'   => 'order 12341423',
            'webhookUrl'   => route('webhooks.mollie'),
            'redirectUrl'   => route('payment.status'), // after the payment completion where you to redirect
        ]);

        $payment = Mollie::api()->payments()->get($payment->id);

        // redirect customer to Mollie checkout page
        return redirect($payment->getCheckoutUrl(), 303);
    }

    /**
     * Page redirection after the successfull payment
     *
     * @return Response
     */
    public function paymentSuccess()
    {
        return view('payments.status');
    }
}
```

**Comment by gabzon** [comment]
Ok sorry I think I misunderstood you. 

it works on https://2dcde7ca4a21.eu.ngrok.io not on my local 

I didnt understand that part. Just to be sure of what I'm doing. It might not be Laravel related but ngrok, once I close the terminal and closes the connection will I lose this or because I added this url to the APP_URL it will always use this a main url for testing?

**Comment by sandervanhooft** [comment]
Ngrok creates a tunnel from the ngrok url to your local machine. The tunnel is gone as soon you close ngrok.

**Comment by sandervanhooft** [comment]
Note that an approach like this is for local development only. No need to set up a tunnel once you've deployed your app on a server.

**Comment by gabzon** [comment]
Ok good to know!
Thank you so much for your help @sandervanhooft

**Comment by sandervanhooft** [comment]
No problem, enjoy!
