### ISSUE TITLE
guzzlehttp/guzzle version ^7.0 support

### ISSUE THREAD

**Issue by m-bosch** [mollie/laravel-mollie#140]
the underlaying package `mollie/mollie-api-php` requires "guzzlehttp/guzzle": "^6.3" instead of the later "guzzlehttp/guzzle": "^7.0" what other packages in our Laravel project required. This conflicts and for this reason we cant use this package at the moment.

**Comment by sandervanhooft** [comment]
Closing this here, will handle issue on `mollie-api-php`.
