### ISSUE TITLE
Redirect url called twice in the same second

### ISSUE THREAD

**Issue by jesse-dijkstra** [mollie/laravel-mollie#142]
We are sending the order confirmation mail job and order job from the controller that is 
connected to the redirect url. Normally every job in the controller is carried out once.
But this time the jobs were carried out twice. This couldn't be possible with a refresh 
because we added checks, this is also the first time it happend in like 40 orders.
![4807873afeeb452f51cf5c03e52d631e](https://user-images.githubusercontent.com/10731323/89618888-481bef00-d88d-11ea-909d-ceb1aa3a5dda.png)

Specs: 
- PHP 7.4.2
- Laravel Framework 6.18.0
- mollie/laravel-mollie v2.8.0.

**Comment by sandervanhooft** [comment]
What's the Mollie dashboard showing for the webhook call responses?

**Comment by jesse-dijkstra** [comment]
> What's the Mollie dashboard showing for the webhook call responses?

Webhook called successfully, it took 0.2 seconds. 

This is the response from the customer service:
The webhook is only triggered once. However I see that the status open has been created twice.

**Comment by sandervanhooft** [comment]
Seems like something on Mollie's end. I'll ask around.

**Comment by sandervanhooft** [comment]
Scratch that. Rereading this: why are you depending on the `redirectUrl` for the order confirmation mail and order job to be sent?

That should depend on the webhookUrl, when the payment has reached status paid.

**Comment by jesse-dijkstra** [comment]
this is because we use the redirectUrl to determine if the user should see the succes page or if not paid succesfully redirected back to pay again. We should move the jobs indeed to the webhook, but isn't it still odd that te redirectUrl is called twice?

**Comment by sandervanhooft** [comment]
From Mollie's end the user is redirected (once) from the checkout. Not much to check what's happening after that.

What I personally do is use a `RedirectFromMollie` controller (and route), that checks the payment status before internally redirecting the customer to the right page within my app. Works great.

**Comment by jesse-dijkstra** [comment]
so in the controller you have something like this?

     if ($payment->isPaid() || $payment->isAuthorized()) {
            $notification = array('message' => 'Betaling in afwachting', 'alert-type' => 'success');
            $route = $this->routePaymentSucces;
        }
        else{
            $notification = array('message' => 'Betaling mislukt, probeer het nog eens', 'alert-type' => 'danger');
            $route = $this->routePaymentFaild;
        }

        return redirect()->route($route)->with($notification);

I'm also curious how you recieve the mollie $payment->id in your controller.

**Comment by sandervanhooft** [comment]
👍  Yes something like that.

The trick with the payment id...

When _creating_ the payment, you receive the payment id. Right before redirecting the customer to Mollie, add that id to the redirectUrl, then update the payment, then redirect the user to Mollie's checkout.

You'll now have the payment id in the RedirectFromMollieController.

**Comment by sandervanhooft** [comment]
```
$payment = mollie()->payments->create([...]);
$payment->redirectUrl = $payment->redirectUrl . '?payment_id=' . $payment->id;

return redirect($payment->getCheckoutUrl());
```

**Comment by jesse-dijkstra** [comment]
that's really clever, thank you so much for the help!

**Comment by sandervanhooft** [comment]
🤓 

No problem, enjoy! 🎉
