### ISSUE TITLE
webhookUrl is not saved in mollie dashboard when creating mollie order

### ISSUE THREAD

**Issue by jesse-dijkstra** [mollie/laravel-mollie#144]
The webhookUrl is shown in the Mollie order resource but not in the Mollie dashboard. Therefore Mollie isn't calling the webhook. 
The documentation states the following : The Orders API invokes a webhook when an order reaches paid or authorized status

The Order resource status is not being updated aswell. example: the order status in Mollie dashboard is : Canceled while the status in the order resource is still created

**Comment by sandervanhooft** [comment]
can you share the calls you are making, and a screenshot of the dashboard?

**Comment by jesse-dijkstra** [comment]
first i'm calling the Mollie::api()->orders->create() and when I data dump Mollie::api()->orders()->get() after the create it shows that the webhookUrl is set but in the dashboard it shows only this information:
![5e7025a1a7a7fd9bdcaf124a44f2015d](https://user-images.githubusercontent.com/10731323/89902106-513af200-dbe6-11ea-8a39-e600138e667e.png)

Then in test mode when I set the status to canceled it changes the status right in the dashboard but when I do data dump Mollie::api()->orders()->get() it is showing the begin payment status which is "created" instead of "canceled"

**Comment by sandervanhooft** [comment]
The `webhookUrl` is part of the Order, the Dashboard screenshot is a Payment.

**Comment by jesse-dijkstra** [comment]
shouldn't the webhookUrl still be set from Mollie::api()->orders->create() ?

**Comment by sandervanhooft** [comment]
> shouldn't the webhookUrl still be set from Mollie::api()->orders->create() ?

There's two webhookUrls. One is set on the Order (when you create it), the other one is set on the Payment (you can pass it in when you create the Order, or update it on the Payment).

> How can you reach the payment status from Mollie::api()->orders()->get()? the payment wasn't embedded when I data dumpt it.

Can you try this?

```php
$order = Mollie::api()->orders()->get($id, ['include' => 'payments']);
dd($order->payments());
```

**Comment by jesse-dijkstra** [comment]
> There's two webhookUrls. One is set on the Order (when you create it), the other one is set on the Payment (you can pass it in when you create the Order, or update it on the Payment).

Thank you very much for clearing this up, now I complete understand the flow between the order and the payment.

> Can you try this?

```
$order = Mollie::api()->orders()->get($id, ['embed' => 'payments']);
dd($order->payments());
```

this did the trick

I have one question left, in the order resource the webhook url is set for the order,
but the webhook url isn't in the order resume in the Mollie dashboard
![4343](https://user-images.githubusercontent.com/10731323/89914154-e513ba80-dbf4-11ea-9280-13f76137cd58.png)

**Comment by sandervanhooft** [comment]
`dd($order->webhookUrl);` ?

**Comment by jesse-dijkstra** [comment]
> `dd($order->webhookUrl);` ?

this returns the order webhookUrl that I set as expected

**Comment by sandervanhooft** [comment]
👍 so functionally it works, but it's not noticeable in the dashboard.

I'll let Mollie support know, and close this issue. Thanks!
