### ISSUE TITLE
sometimes RedirectFromMollie controller isn't triggered in Ngrok

### ISSUE THREAD

**Issue by jesse-dijkstra** [mollie/laravel-mollie#145]
##  Expected Behavior
Redirect to the success or failed page

## Current Behavior
Sometimes in test mode I'm not redirected in the RedirectFromMollie controller. 
In this situation the current url matches the RedirectFromMollie route url but nothing happens.
The screen stays blank until I do a refresh, then everything works as it should and I get redirected to
the success or failed page. 

## Context
This isn't happening with a specific payment method (had it with Ideal aswell as Klarna pay later)
This happens random once in a while.

## Your Environment
PHP 7.4.2
Laravel Framework 6.18.0
mollie/laravel-mollie v2.8.0.
test mode

I'm wondering if this is a bug or has something to do with Ngrok and if it also could happen in the production enviroment, since it would be pretty weird for customers to recieve a blank screen after paying.

**Comment by sandervanhooft** [comment]
ngrok imposes a throttle limit on the amount of calls. I suspect this to be the cause (ran into this myself a few times). You can significantly increase the threshold if you sign up for a free account.

Alternatively, try [Expose](https://beyondco.de/docs/expose/introduction) instead of ngrok.

**Comment by jesse-dijkstra** [comment]
> ngrok imposes a throttle limit on the amount of calls. I suspect this to be the cause (ran into this myself a few times). You can significantly increase the threshold if you sign up for a free account.
> 
> Alternatively, try [Expose](https://beyondco.de/docs/expose/introduction) instead of ngrok.

Thank you very much for clearing this up, I will give Expose a try
