### ISSUE TITLE
paypal payment method not showing on checkout page

### ISSUE THREAD

**Issue by elmegaito** [mollie/laravel-mollie#146]
Hi everyone, 
I followed the instructions to make a one-time payment with Mollie (and it works). In the Mollie dashboard I have activated the Paypal payment method as well as credit card, but the Paypal payment method does not appear on the checkout page (and that is the issue). I contacted the technical support of Mollie and Paypal and they said the connection between Mollie and Paypal is ok. There is something i am missing on the Laravel side (the things i had to handle to manage to enable users to pay with Paypal)?
Can you help me? I google a lot to resolve this, but with no luck.
Thank you

**Comment by sandervanhooft** [comment]
Can you share your code?

**Comment by elmegaito** [comment]
Hi,
here the code of the controller method (i removed some app specific code that is not of interest, like the redirect routes)
```
// ...
$user = Auth::user();
if ($user->mollie_customer_id == null) {
    $customer = Mollie::api()->customers()->create([
        'name' => $user->name,
        'email' => $user->email,
    ]);
    $user->mollie_customer_id = $customer->id;
    $user->save();
    $user = $user->fresh();
}

$payment = Mollie::api()->payments()->create([
    'amount' => [
        'currency' => 'EUR',
        'value'    => 12
    ],
    'customerId'   => $user->mollie_customer_id,
    'sequenceType' => 'first',
    'description'  => 'the description ',
    'redirectUrl'  => <the redirect route>,
    'webhookUrl'   => <the webhook route>,
]);

$payment = Mollie::api()->payments()->get($payment->id);

return redirect($payment->getCheckoutUrl(), 303);
```
Thank you

**Comment by sandervanhooft** [comment]
Did you confirm with Mollie support that your account is correctly set-up with PayPal for **_recurring_** payments, not only one-offs?

**Comment by elmegaito** [comment]
Hi, after your message I requested PayPal support to enable recurring payments as you suggested. I thought it wasn't necessary for one-time payments. When they will enable it, I will try to pay again to see if paypal finally shows up between the valid  payment methods.
Thank you for your support!

**Comment by sandervanhooft** [comment]
No problem. I expect this will do the trick. I'll close the issue for now, let me know if it should be reopened.

**Comment by elmegaito** [comment]
Hi, paypal said that they have activated recurrent payment (for the sandbox account for now), but i still cant see paypal on the available payment methods and if "force paypal method"  with the following code
```
$payment = Mollie::api()->payments()->create([
            'amount' => [
                'currency' => 'EUR',
                'value'    => 10,
            ],
            'method' => 'paypal',
            'customerId'   => $user->mollie_customer_id,
            'sequenceType' => 'first',
            'description'  => 'description',
            'redirectUrl'  => 'the redirect route',
            'webhookUrl'   => 'the webhook route',
        ]);
```
i will get the error in the image.

![errore_laravel](https://user-images.githubusercontent.com/70273284/91718220-421ae480-eb93-11ea-9a62-02a7f8690f87.png)

So i think i have a bad configuration in my laravel application. There is something i need to do to make the mollie laravel client knows about paypal (paypal client id and secrets)?
Thank you in advance

**Comment by sandervanhooft** [comment]
This is something in the configuration of PayPal/Mollie, not your app. Best to contact Mollie support if you have set up PayPal recurring correctly now. Note that it also may take some time before the changes at PayPal are visible to Mollie. But I don't think that should take longer than 24h.
