### ISSUE TITLE
Mollie payment shows wrong status

### ISSUE THREAD

**Issue by jesse-dijkstra** [mollie/laravel-mollie#147]
I have this is issue with the following situation: A customer made a payment with Paypal so the status went to paid as aspected. Later the customer chargebacked the payment and it shows the correct payments status in Mollie dashboard, but in the Mollie payments resource it still show 'paid' instead of 'chargeback'

**Comment by sandervanhooft** [comment]
This is actually correct behavior.

**Comment by jesse-dijkstra** [comment]
How can I see it's a chargeback in the payments resource + the webhook gets triggered twice in the paid statement when the status stays the same in this situation

**Comment by sandervanhooft** [comment]
I agree it's not an ideal situation.

You can check the chargebackAmount to see if there's a chargeback.

Regarding the webhook, I'm thinking of updating it once the payment has reached status paid to avoid double processing etc.. 

I.e. change it into webhooks/mollie/payments/_aftercare_ and use a dedicated AftercareController.

Note that multiple chargebacks and refunds can occur after the status paid has been reached, so it may make sense to track chargeback amounts and refund amounts locally.

**Comment by jesse-dijkstra** [comment]
Thank you very much for your response, I found out that can get the chargeback with the payment resource like this: 

```
Mollie::api()->payments()->get($request->id, ['embed' => 'chargebacks']);
$payment->chargebacks()->count < 1
```

this way you can if a payment has a chargeback and avoid double processing and for example save the chargeback info.
