### ISSUE TITLE
Losing checkout link in get() response when using przelewy24 payment method 

### ISSUE THREAD

**Issue by HarryLee186** [mollie/laravel-mollie#149]
When using the przelewy24 payment method, the checkout link that is returned in the API response is null

## Expected Behavior
The checkout link should return correctly, such as:
![image](https://user-images.githubusercontent.com/34167106/93817789-5bbec180-fc51-11ea-9e5e-41ff86adc319.png)

## Current Behavior
The checkout link is null, shown below:
![image](https://user-images.githubusercontent.com/34167106/93817857-71cc8200-fc51-11ea-81d7-34783feffaf5.png)

## Steps to Reproduce (for bugs)

1. Using Laravel 6, add `"mollie/laravel-mollie": "2.7.0",` to your composer.json and run a composer install
2. Add the following code to a controller:
```
use Mollie\Laravel\Facades\Mollie;

public function preparePayment()
{
    $payment = Mollie::api()->payments->create([
        "amount" => [
            "currency" => "EUR",
            "value" => "10.00" // You must send the correct number of decimals, thus we enforce the use of strings
        ],
        "description" => "Order #12345",
        "redirectUrl" => route('order.success'),
        "webhookUrl" => route('webhooks.mollie'),
         "method" => 'przelewy24',
        "metadata" => [
            "order_id" => "12345",
        ],
    ]);

    $payment = Mollie::api()->payments->get($payment->id);

    // redirect customer to Mollie checkout page
    return redirect($payment->getCheckoutUrl(), 303);
}
```
3. Run the function, it'll likely throw a redirect error as the checkout url is null. You can dump out `$payment` before the return to see the null checkout url.

## Context
Trying to offer this payment method in an e-commerce application, and due to the null checkout url, when redirecting it's simply giving an error.

## Your Environment

* Version used: Laravel: 6.1, laravel-mollie: 2.7.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Google Chrome
* Operating System and version (desktop or mobile): Developing on Windows, but this issue happens on Ubuntu too
* Link to your project: N/A

**Comment by sandervanhooft** [comment]
That's strange. I've asked Mollie support to look into this.

**Comment by sandervanhooft** [comment]
What is the status of the payment?

**Comment by sandervanhooft** [comment]
The checkoutUrl will only be available on net-yet-paid-payments, so status `open`.

**Comment by HarryLee186** [comment]
This is before getting to the payment screen, using the code snippet from this repo's readme. So yes I would imagine the payment status would be open(this snippet works perfectly with other methods as outlined in my issue)

**Comment by sandervanhooft** [comment]
This behaviour is a bit weird, but if you remove this obsolete line it works:

```php
$payment = Mollie::api()->payments->get($payment->id);
```

**Comment by sandervanhooft** [comment]
I'll ask Mollie support if they can fix this in the api. Nice catch!

Closing this for now, let me know if it should be reopened.
