### ISSUE TITLE
Mollie Connect | Authorization code doesn't exist or is invalid for the client

### ISSUE THREAD

**Issue by salman15** [mollie/laravel-mollie#150]
I've added followed the steps on [https://docs.mollie.com/oauth/overview](url) and on mollie connect documentation and I've connected my laravel 7 app to mollie with my `redirect_url, client_id and client_secret`. However the code I get back in the `redirect_login` doesn't seem to authenticate when I make a post request from `https://api.mollie.com/oauth2/tokens`.

## Expected Behavior
I expect the auth code I get back in the url to be accepted when making a post request.

## Current Behavior
I get an error status 400 bad request with a response 

`{
    "error": "invalid_grant",
    "error_description": "Authorization code doesn't exist or is invalid for the client"
}`

## Steps to Reproduce (for bugs)

1. Install laravel
2. Install Mollie
3. Install Socialite
4. Copy example from Mollie's docs
5. Add in your own app credentials
6. Sign in with a Mollie account
7. Use the redirect url's code param to make a post request

## Context
I'm trying to use mollie connect to make payment requests on behave of my clients

## Your Environment
I'm running my app on a plesk onyx 17.x with php7.3.x with my composer file below

` "require": {
        "php": "^7.3.22",
        "alymosul/laravel-exponent-push-notifications": "^2.1",
        "beyondcode/laravel-websockets": "^1.6.1",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0",
        "guzzlehttp/psr7": "^1.6.1",
        "laravel/framework": "^7.25",
        "laravel/helpers": "^1.3",
        "laravel/passport": "^9.3.2",
        "laravel/socialite": "^5.0",
        "laravel/tinker": "^2.4.2",
        "laravel/ui": "^2.2",
        "mollie/laravel-mollie": "^2.1",
        "nesbot/carbon": "^2.0",
        "pusher/pusher-php-server": "^4.1",
        "tymon/jwt-auth": "1.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.4",
        "filp/whoops": "^2.7.3",
        "fzaninotto/faker": "^1.9",
        "mockery/mockery": "^1.3",
        "nunomaduro/collision": "^5.0.",
        "phpunit/phpunit": "^9.3",
        "sven/artisan-view": "^3.1"
    },`

**Comment by sandervanhooft** [comment]
Thanks for reporting this. Let me try and reproduce the error here.

**Comment by sandervanhooft** [comment]
Can you share a code example which triggers this error?
