### ISSUE TITLE
So im using laravel 7.28.4 and i want to use mollie so i ran the command ''composer require mollie/laravel-mollie:^2.0" but it says that it's not available for laravel 7.28.4. The supported versions are laravel 5 version. Is there another way i can use mollie in laravel? 

### ISSUE THREAD

**Issue by Heesel** [mollie/laravel-mollie#151]
a

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sandervanhooft** [comment]
V2 has been tested to support Laravel 6, 7 and 8 - based on the information provided I cannot tell what is causing the issue with your installation.
