### ISSUE TITLE
No parameters on RedirectUrl and WebhookUrl not called

### ISSUE THREAD

**Issue by EricKarijo** [mollie/laravel-mollie#154]
public function createMolliePayment( Order $order ) {

        // TODO: get restaurant api key here..

        Mollie::api()->setApiKey( "test_keyjdhfkjdhfkjdfdjs" );

        $restorant = Restorant::findOrFail($order->restorant_id);

        $ord_total = sprintf("%.2f", floatval($order->delivery_price + $order->order_price + $order->static_fee ));

        $oid = "cca_" . time();
        $payment = Mollie::api()->payments->create([
            // "id"            => $oid,
            "amount"        => [
                "currency"  => "EUR",
                "value"     => $ord_total, // You must send the correct number of decimals, thus we enforce the use of strings
            ],
            "description"   => "Bestelling #" . $order->id . " bij '" . $restorant->name . "'",
            "redirectUrl"   => route('mollie.webhooks.redirect'),  // route('orders.index'),
            "webhookUrl"    => route('mollie.webhooks.normal'), // route('webhooks.mollie'),
            "metadata"      => [
                    "order_id"      => $order->id,
                    "test_mode"     => 'Ja',
                ],
        ]);

        $payment_id = $payment->id;

        // redirect customer to Mollie checkout page
        // return redirect($payment->getCheckoutUrl(), 303);
        return redirect()->away($payment->getCheckoutUrl(), 303 );
    }

my route in web.php:
        Route::get('webhooks/mollie/redirected', 'MollieController@handleMollieWebhookRedir')->name('webhooks.redirect');

my webhookcode:
     /* Obtain Mollie payment information.
     * @return void
     */
    public function handleMollieWebhookRedir( Request $request )
    {        

        if ( !$request->has( 'id' )) {
            return redirect()->route('orders.index')->withStatus(__('Order created.') . ' -R- ' . __("Payment status") . ': ' . 'Betaling is geannuleerd!' );
        }
        $id = $request->id;

        $payment = Mollie::api()->payments()->get( $id );
        $orderId = $payment->metadata->order_id;

        .....
}

## Expected Behavior
In my redirect controller I was expecting a $request with payment info in it.
But there is no payment info in the request.

## Current Behavior
No payment info in $request

## Your Environment
my composer.json require section:
        "laravel/cashier": "^12.4",
        "laravel/framework": "^7.29",
        "laravel/helpers": "^1.4",
        "laravel/socialite": "^5.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.4",
        "mollie/laravel-mollie": "^2.0",

Please help in this.
What am I doing wrong?

**Comment by sandervanhooft** [comment]
Try

`$id = request->input('id');`

**Comment by EricKarijo** [comment]
Hi Sander,
Does not work with $id = $request->input('id');
Cause we are not in a form.
 
I found another way to handle.

I'm closing this issue
