### ISSUE TITLE
Mollie::api()->profiles()->create returns empty screen.

### ISSUE THREAD

**Issue by EricKarijo** [mollie/laravel-mollie#155]
trying to create a profile when customer does not have one already by calling this:

              Mollie::api()->setAccessToken($token);

             $profile = Mollie::api()->profiles()->create([
                    "name"          => $current_user->restorant->name,
                    "website"       => "https://www.afhaal.nu",
                    "email"         => $current_user->email,
                    "phone"         => $current_user->phone,
                    "categoryCode"  => "5399",
                    "mode"          => "test",
                ]);

This call returns nothing.

No error(s) on screen.

## Expected Behavior
As of doc I was expecting a return value from the call as stated in doc:

Response
201 application/json

A profile object is returned, as described in Get profile.

https://docs.mollie.com/reference/v2/profiles-api/create-profile

## Current Behavior
Nothing is return back.
No response.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sandervanhooft** [comment]
Hi @EricKarijo,

Can you check that both the `profiles.read` and `profiles.write` oauth scopes are enabled for your app token?

https://docs.mollie.com/oauth/permissions

**Comment by EricKarijo** [comment]
hi @sandervanhooft , seems it's our part which was not working.
Thanks btw.
I will close this issue.
