### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by jnoordsij** [mollie/laravel-mollie#157]
[PHP8](https://www.php.net/releases/8.0/en.php) has been released. Currently `composer.json` in this project does not support it.

## Expected Behavior

PHP8 supported by this project.

## Current Behavior

Composer does not allow installing this as dependency on projects with php version `"php": "^8.0"`.

**Comment by sandervanhooft** [comment]
We'll need to fix this on `mollie/mollie-api-php` first.

After that this package is ready to be released with php8 support.

**Comment by ciungulete** [comment]
@sandervanhooft , this is closed by #159

**Comment by sandervanhooft** [comment]
@ciungulete True! Thanks!

**Comment by jnoordsij** [comment]
Great, thanks for fixing this!
