### ISSUE TITLE
Missing profileMethods function in MollieApiWrapper

### ISSUE THREAD

**Issue by e-defix** [mollie/laravel-mollie#163]
The function profileMethods is missing in MollieApiWrapper.php.

Please add this function.

**Comment by sandervanhooft** [comment]
Good catch, we'll look at it.

**Comment by e-defix** [comment]
When will this be merged? I'm waiting for this merge for my integration with Mollie Connect

**Comment by sandervanhooft** [comment]
Available on 2.14.0. Thanks for noticing.
