### ISSUE TITLE
It there any Way to get the Refund with the RefundToken?

### ISSUE THREAD

**Issue by christoph-werker** [mollie/laravel-mollie#165]
I am wondering if there is any way to get the Refund or Payment with the RefundToken beginning with *re_123123123*?
I am working on the Accounting for my company and i got only the RefundToken with the RefundToken for transactions but no more information...

**Comment by sandervanhooft** [comment]
Unfortunately you'll need both the `paymentId` and the `refundId` ([docs](https://docs.mollie.com/reference/v2/refunds-api/get-refund#example)).

Optionally you can [paginate](https://docs.mollie.com/reference/v2/refunds-api/list-refunds#example) through all refunds across all payments and build a lookup table locally.
