### ISSUE TITLE
Not getting into the webhook/500

### ISSUE THREAD

**Issue by tnf20** [mollie/laravel-mollie#166]
Hi there,
 
I have a little problem with getting into the webhook. I also want to make changes to my database when the payment isPaid after the payment.

## Current Behavior
In my Mollie dashboard I can see that the webhook URL is called but getting a 500 error message.
![dash](https://user-images.githubusercontent.com/79840351/109484585-e5847d80-7a80-11eb-881d-b29f3b1f2f74.jpg)

## Steps to Reproduce (for bugs)

![image](https://user-images.githubusercontent.com/79840351/109484868-3eecac80-7a81-11eb-8605-535012205a0e.png)

The webhook
![image](https://user-images.githubusercontent.com/79840351/109484899-490eab00-7a81-11eb-93b2-9b8123c18e03.png)

Redirect function
![image](https://user-images.githubusercontent.com/79840351/109484992-693e6a00-7a81-11eb-9b6d-d361219b618e.png)

And the web.php
![image](https://user-images.githubusercontent.com/79840351/109485065-82471b00-7a81-11eb-828c-0ef6575e0e8d.png)

## Your Environment
"mollie/laravel-mollie": "^2.11"
"laravel/framework": "^7.24",

**Comment by sandervanhooft** [comment]
This error happens when there's an error in the code handling the webhook. Best place to start debugging in this case are your Laravel logs.

**Comment by tnf20** [comment]
Hi Sander, thanks for your response. 

There is nothing inside my Laravel logs that has anything in common with the payment process.

**Comment by tnf20** [comment]
> Hi Sander, thanks for your response.
> 
> There is nothing inside my Laravel logs that has anything in common with the payment process.

Found the problem. 

```
$order = Order::findOrFail($order->id);
        $this->decreaseQuantities();
        $order->is_paid = 1;
        $order->save();

        Mail::to($order->user->email)->send(new OrderPaid($order));
        
        \Cart::clear();
        return view('thankyou');
```

If I use this in the public function handle it's returns the 500 error.

**Comment by sandervanhooft** [comment]
This line seems to be the issue:

$order = Order::findOrFail($order->id);

Should be:

$order = Order::findOrFail($payment->id);

Or something like that, depending on how you store your orders.

**Comment by tnf20** [comment]
This is how I store the orders:
![image](https://user-images.githubusercontent.com/79840351/109624850-f3003d00-7b3e-11eb-9ea5-3bc35b9e1dfd.png)

So I think using $order->id should be the right way. If I use payment->id I get a 404 in return from the webhook.

**Comment by Jubeki** [comment]
You use $order->id before you fetched the Order from the database. This means you are accessing a not existing variable.

`$order = Order::findOrFail($payment->id);`
this uses instead the payment id.
findOrFail will look at the `id` column but I think you want to look at the `payment_id` column in which you reference the payment id.

**Comment by tnf20** [comment]
I'm not saving the payment_id to the database. Could that be the problem?

**Comment by tnf20** [comment]
Made some changes to my database. Payment_id is now saved in my database. I also changed the handle function.

```
public function idealCheckout(Order $order, Request $request)
    {
        $amount = $order->grand_total;
        $issuer = $order->ideal_option;

        $payment = Mollie::api()->payments()->create([
            'amount' => [
                'currency' => 'EUR',
                'value' => $amount,
            ],
            'method' => 'ideal',
            'issuer' => $issuer,
            'locale' => 'nl_NL',
            'description' => 'Afrekenen',
            'redirectUrl' => route('ideal.success'),
            'webhookUrl' => route('webhooks.mollie'),
        ]);

        $order->payment_id = $payment->id;
        $order->is_paid='';
        $order->save();

        return redirect($payment->getCheckoutUrl(), 303);
    }

    public function handle(Request $request, Order $order)
    {
        if(! $request->has('id') ) {
            return;
        }

        $payment = Mollie::api()->payments()->get($request->id);
        $statusOfPayment='';

        if ($payment->isPaid() && !$payment->hasRefunds() && !$payment->hasChargebacks()) {
            $statusOfPayment='paid';
        } elseif ($payment->isOpen()) {
            $statusOfPayment='open';
        } elseif ($payment->isPending()) {
            $statusOfPayment='pending';
        } elseif ($payment->isFailed()) {
            $statusOfPayment='failed';
        }

        $order = Order::where('payment_id', $request->id)->first();
        $order->is_paid = $statusOfPayment;
        $order->save;
    }
```

Now is the webhook called successfully. The only problem left is that the $statusOfPayment is not being saved to the database. If I use 'id' instead of 'payment_id' I get 500 in response from the webhook.

![image](https://user-images.githubusercontent.com/79840351/109841756-a7868580-7c49-11eb-8b76-28b6ef773078.png)
