### ISSUE TITLE
Exchange rates for multicurrency

### ISSUE THREAD

**Issue by boryn** [mollie/laravel-mollie#168]
Let's say I accept the payment in GBP. Later I'm able to fetch the settlement amount in EUR.

But what if I needed to express the paid amount in NOK? The conversion could be done at the moment of querying it, not necessarily at the date of the payment. It is needed to display approximate amounts in any other supported currency.

Does Mollie offer any exchange rate method before we create the payment, both from and to EUR? Or the exchange rates are published? So the question is how to express an amount in EUR in any other currency?

#multicurrency #multicurrencies

**Comment by sandervanhooft** [comment]
Mollie does not support conversion _calculations_ as a service. This is best handled in your app, as cases like these are super specific to your business.
