### ISSUE TITLE
Could you advice me on importing recurring subscriptions?

### ISSUE THREAD

**Issue by ralphjsmit** [mollie/laravel-mollie#170]
Hey,

Thanks for maintaining this Mollie client.

I'm doing some research about moving existing subscriptions to the Laravel client and I need a bit of advice. It'd be great if you could tell me if the situation described is possible and if I understood everything correctly.

### Current situation
Let me first explain the current situation. Our company in IT-help offers customers the option to subscribe to a certain plan. This plan gives users several benefits, like a reduced hourly fee and access to downloads like Microsoft Office. Most users initially pay via iDeal and the subscription is renewed each year via SEPA and by making use of the mandate.

We have about 700 customers and almost 400 of them are managed with a simple WordPress installation.

- WooCommerce
- WooCommerce subscriptions
- Mollie Payments for WooCommerce

This means that billing and order info is managed by WooCommerce, subscription management is done by WooCommerce Subscriptions, which then sends the actual renewal payment to Mollie. And Mollie has the mandates and also some info.

### What do we want?
We want to move all the subscriptions to a custom application. WooCommerce slows down the website and it is (almost) impossible to change the subscription price for existing customers.

This would give us several benefits:

1. We fully control the data
2. We can give users their own 'dashboard' to download software etc (and perhaps more later)
3. We are in charge of the renewal price charged to existing customers

We'd like to first move the 400 subscriptions to Laravel and the rest perhaps later.

### Can I do this like this?

1. Build the application and make sure that new signups work. 
2. Create a way to import subscriptions based on the way they're exported.
3. Export customers, e.g. with the [WebToffee exporter](https://www.webtoffee.com/import-and-export-woocommerce-subscriptions-orders/). This data would include at least the `customer_id` (is this the same id as in Mollie??), the next renewal date.
4. Get the above data into our Laravel database.
5. Check periodically if a customer needs to be charged.
6. Retrieve a customer in some way. What would be the best way to do that? I'd like to do it similar to this, though not `create()`, but `retrieve($customer_id)` (or sth similar).
```php
$customer = Mollie::api()->customers()->create([
    'name'  => 'John Doe',
    'email' => 'john@doe.com',
]);
```
7. Get a mandate like this:
```php
$mandates = Mollie::api()->mandates()->listFor($customer);
```
8. Charge like this
```php
 $payment = Mollie::api()->payments()->create([
    'amount' => [
        'currency' => 'EUR',
        'value'    => '25.00', // You must send the correct number of decimals, thus we enforce the use of strings
    ],
    'customerId'   => $customer->id,
    'sequenceType' => 'recurring',
    'description'  => 'Direct Charge',
    'webhookUrl'   => route('webhooks.mollie'),
]);
```
9. Listen to the [webhook like this](https://github.com/mollie/laravel-mollie/blob/master/docs/webhook.md).
10. If payment is successful, change the renewal date to a year later.
11. Do some extra stuff like sending an email.

## Would the above method work? What do I need to watch out for?

1. Any advice on exporting WooCommerce Subscriptions?
2. Is the `customer_id` in WooCommerce subscriptions the same as in the Mollie dashboard?
3. How to retrieve a `$customer` with the `customer_id`
4. Do you recommend to use the Cashier package with this?
5. I'm a bit confused between Mollie Recurring API and eCurring. Could you tell me more about this?
5. Any advice?

Many thanks!

Ralph

**Comment by sandervanhooft** [comment]
Hi @ralphjsmit Why not port it over to [cashier mollie](https://github.com/laravel/cashier-mollie) instead?

**Comment by ralphjsmit** [comment]
Hey Sander, thanks for your fast reply.

I considered that, but a custom solution seemed simpler. But perhaps you're right.

Though that still leaves me with a few questions:

1. If I want to import current subscriptions with the Cashier package, how would you do that? I mean, when you create a subscription, how do you prevent Mollie from immediately charging money, whilst the subscription could still be running for months?
2. I read the below. Is this checked in the database or via the Mollie API? And if it is checked in the database, can I combine that with this package when I make some kind of importer?

> If the customer already has a valid Mollie mandate, the $result will be a Subscription.
If the customer has no valid Mollie mandate yet, the $result will be a RedirectToCheckoutResponse, redirecting the customer to the Mollie checkout to make the first payment. Once the payment has been received the subscription will start.

3. Is it correct that I need to create a `$user` first and then use this?

```php
$user = User::find(1);
// Make sure to configure the 'premium' plan in config/cashier_plans.php
$result = $user->newSubscription('main', 'premium')->create();
```


4. I saw the announcement post on your website ;-). Are there more guides?
5. Could you explain more about invoices?

Thanks!

**Comment by sandervanhooft** [comment]
First of all, please note that I don't know how WooCommerce handles the subscriptions.

I.e. Cashier Mollie does **not** use Mollie's subscription API, but uses the Payments API and handles the scheduling logic within the package. This gives more flexibility. If WooCommerce uses the Subscriptions API, you'll need to stop the Subscription when Cashier takes over.

A few steps:

1. Cashier Mollie uses the billable model's `mollie_customer_id` and `mollie_mandate_id` fields, typically on the `users` table. You could import these fields from your current WooCommerce setup.

1. Define the subscription plans in the `cashier_plans` config. If you have a lot of plans you can choose to use a custom plan repository instead, i.e. backed by a database table.

1. When you're ready, you can start the subscription by using the `$billable->newSubscription()->...` methods. It's not possible to schedule a start date, so this should be run at the moment the subscription should start.

We're in the process of preparing the alpha for Cashier Mollie v2. Once it's ready there will be a dedicated documentation website and if I can find the time I'll even try and record some videos. For now, most of the information is within the repository's readme. Also about invoices :).

If you have specific questions about cashier, please open an issue ticket there.

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
