### ISSUE TITLE
Not able to get into webhook

### ISSUE THREAD

**Issue by XavegX367** [mollie/laravel-mollie#171]
I am trying to check my payments by using the webhook, but I don't know how to make it work since I am very new to webhooks. The website itself is a live website, so it is not local or anything

Here is the error in Mollie:
![image](https://user-images.githubusercontent.com/76949970/119514486-592ee180-bd75-11eb-9eec-0bd8e27fadca.png)

Here is my MollieController:
![image](https://user-images.githubusercontent.com/76949970/119514270-28e74300-bd75-11eb-8e1e-6572cac31316.png)

Here the MollieWebhookController:
![image](https://user-images.githubusercontent.com/76949970/119515054-d2c6cf80-bd75-11eb-8b43-14eef67cd287.png)

I didn't change a single line in the WebhookController, since it doesn't even get there (I think)

and as final the web.php:
![image](https://user-images.githubusercontent.com/76949970/119515228-f8ec6f80-bd75-11eb-8eb2-2144abfada1f.png)

Hopefully this problem can be solved, since I am getting very tired of it :)

**Comment by Jubeki** [comment]
Could you please share the error which you can find in your log files?

**Comment by Jubeki** [comment]
Also you should probably put the webhook Route into the `api` middleware group instead of `web`.
Because Laravel will try to check the csrf-Token on a post request in the web group.
You could also ignore the path in the Middleware `app/Http/Middleware/VerifyCsrfToken.php`

**Comment by XavegX367** [comment]
> Also you should probably put the webhook Route into the `api` middleware group instead of `web`.
> Because Laravel will try to check the csrf-Token on a post request in the web group.
> You could also ignore the path in the Middleware `app/Http/Middleware/VerifyCsrfToken.php`

I am already ignoring the webhook as shown in the screen below
![image](https://user-images.githubusercontent.com/76949970/119543587-1975f300-bd91-11eb-89a3-0cb99f07feeb.png)

When looking at the logs, I am only able to find 1 error and I am not sure if it has something to do with Mollie

But this is the error:

> [2021-05-25 16:25:22] local.ERROR: Unresolvable dependency resolving [Parameter #0 [ <required> $method ]] in class GuzzleHttp\Psr7\Request {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> $method ]] in class GuzzleHttp\\Psr7\\Request at /home/public/sites/webdata/vendor/laravel/framework/src/Illuminate/Container/Container.php:1032)
> [stacktrace]

If this is not the error, that I should post please tell me what I should be looking for.

**Comment by Jubeki** [comment]
Do you import `Illuminate\Http\Request` or `GuzzleHttp\Psr7\Request`.
Otherwise I have no clue right now. Maybe @sandervanhooft can help you.

**Comment by sandervanhooft** [comment]
Jubeki is asking the right question.

Also, what version are you using of:

- mollie/mollie-api-php
- mollie/laravel-mollie

? You can use `composer show <vendor/package-name>` to retrieve local package information.

**Comment by XavegX367** [comment]
> Do you import `Illuminate\Http\Request` or `GuzzleHttp\Psr7\Request`.
> Otherwise I have no clue right now. Maybe @sandervanhooft can help you.

Oh my bad haha, thanks! I was indeed using the 'GuzzleHttp\Psr7\Request' I changed it and now it works!
![image](https://user-images.githubusercontent.com/76949970/119559380-de7cbb00-bda2-11eb-82b1-8c1db2abc6be.png)

Thank you both for the quick reactions and the help!
