### ISSUE TITLE
Webhook failed with a 405 status

### ISSUE THREAD

**Issue by nakigami** [mollie/laravel-mollie#172]
Hi everyone, 
I created a webhook to send an email of a specific order, and the webhook executes perfectly but the problem is that mollie sends a reccurrent request to the same webhook which send the email multiple times :(
PS : I already added the route in VerifyCsrfToken.php to except it from the CSRF token verification process.

## Expected Behavior
The webhook should be executed one time

## Current Behavior
The webhook is executed many times due to the detected status (405 Method not allowed), and i used a post route and always I'm getting the same error, and i changed to any and always the same thing occcurs.

## Possible Solution
- Control the status of the webhook
- Control the number of the sent request if a webhook has a 405 status

## Steps to Reproduce (for bugs)
1. Create an order
2. Pass the payment process
3. The webhook is executed but due to it's status of 405 Method Not Allowed, it has been executed many times which send the confirmation email many times

## Context
Here is my current route (before i used 'POST') : 
Route::any('/webhook_payment/{order}', [PaymentController::class, 'handleWebhookFirstPayment'])->name('webhook.payment');

## Your Environment
* Laravel 8

**Comment by sandervanhooft** [comment]
There's multiple events for which the webhook can get called (paid, canceled, failed, refund performed, refund failed, chargeback received). This also means that a webhook can get called multiple times on a single payment.

Best is to check what actually happened (Mollie unfortunately offers no easy way for this yet), and optionally keep track of what emails were sent already.

A trick I often use is when reaching status paid, I update the webhook url to one that is dedicated to handling aftercare (refunds and chargebacks), to simplify the controller logic.

**Comment by nakigami** [comment]
Thanks for your fast resply first, honestly it was my fault i didn't saw in the doc that i should return a 200 status, that's why now i return a status of 200 and i added a flag column to my table and after the first email sending operation i change the flag value ;) and now even if Mollie sends multiple requests to the webhook the email is not be sent again.

**Comment by sandervanhooft** [comment]
Great, thanks for following up. Enjoy!
