### ISSUE TITLE
Problem by install with composer

### ISSUE THREAD

**Issue by dataxlamsterdam** [mollie/laravel-mollie#176]
Hi Sander,

If I install the package with composer version above 2.0 as specified in your manual there will be a error:

Problem 1
    - Root composer.json requires mollie/laravel-mollie 2.0 -> satisfiable by mollie/laravel-mollie[v2.0.0].
    - mollie/laravel-mollie v2.0.0 requires illuminate/support ^5.5 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
   
When I run the installation as; composer install mollie/laravel-mollie without version there is no error and version 2.15 will be add and installed.
Just start this issue to let you know.

**Comment by sandervanhooft** [comment]
```
composer create-project laravel/laravel laravel-mollie-install-test
cd laravel-mollie-install-test
composer require mollie/laravel-mollie:^2.0
```

Works fine. Did you perhaps forget the `^`?

**Comment by Afzaal565** [comment]
I have also facing same issue while I am writing composer require mollie/laravel-mollie:^2.0

**Comment by striderxfossility** [comment]
Me to, probably because i use laravel 9.0, illuminate/support is inside the laravel/framework package and so i cant be used.

**Comment by dilanakilamapa** [comment]
Use this it's work for me composer require mollie/laravel-mollie:*
