### ISSUE TITLE
What's the default timeout for a payment to get auto cancelled?

### ISSUE THREAD

**Issue by Thedonsolo** [mollie/laravel-mollie#179]
## Context

I would like to know when a payment is automatically cancelled after the user has navigated to the Mollie payment page.
Also, whereto is he redirected then?

**Comment by sandervanhooft** [comment]
All redirects (success, paid, canceled) will be to the redirectUrl provided when creating the payment.

More information, including specific expiration times, here:

https://docs.mollie.com/payments/status-changes
