### ISSUE TITLE
Failed calling webhook statuscode 500 (Internal Server Error)

### ISSUE THREAD

**Issue by XavegX367** [mollie/laravel-mollie#181]
Mollie suddenly is not able to call the webhook

The webhook was fully functional. but suddenly it doesn't do anything and I am not getting a single output in my logs. I include metadata with my orders, but there is nothing wrong with that. It is the exact same as when it worked

Hopefully anyone can help?

**Comment by sandervanhooft** [comment]
This means something is going wrong within your Laravel application.

What happens if you make a similar post request to the webhook, but manually? I.e. with Postman or curl?

**Comment by XavegX367** [comment]
I don't know if I used the program correct, but it is showing this error: 

Mollie\Api\Exceptions\ApiException: [2021-12-21T10:29:41+0000] Invalid payment ID: ''. A payment ID should start with 'tr_'. in file /home/public/sites/www.*******.nl/webdata/vendor/mollie/mollie-api-php/src/Endpoints/PaymentEndpoint.php on line 88

**Comment by Jubeki** [comment]
Can you please share your Controller where you receive the webhook?

And also what ID did you include in you test request?
Your get request should be a POST request containing an Payment ID starting with `tr_` (Best would be a test payment)

**Comment by XavegX367** [comment]
So I am not using the program correct since I have used a test id: 'tr_ghw2JGxrcf'

**Comment by XavegX367** [comment]
Okay, so I only dropped the payment ID into the post and now I am getting the same list as I do when I click on the test order on the mollie website. Unfortunately I am still getting a 500 internal server error

**Comment by Jubeki** [comment]
Please share your Webhook Controller where you receive the Webhook from Mollie. Otherwise just the information that you receive a 500 error is not enough.

**Comment by XavegX367** [comment]
So this is my handle function

public function handle(Request $request) {
        $paymentId = $request->input('id');
        $payment = Mollie::api()->payments->get($paymentId);
        if ($payment->isPaid())
        {
            $completedOrder = new orders;
            $completedOrder->MollieID = $paymentId;
            $completedOrder->Klantnummer = $payment->metadata->customerid;
            $completedOrder->Datum = $payment->metadata->datum;
            $completedOrder->Betaald = 1;
            $completedOrder->Bedrag = $payment->metadata->bedrag;
            $completedOrder->Postcode = $payment->metadata->Postcode;
            $completedOrder->Plaats = $payment->metadata->Plaats;
            $completedOrder->Straat = $payment->metadata->Straat;
            $completedOrder->Huisnummer = $payment->metadata->Huisnummer;
            $completedOrder->Toevoeging = $payment->metadata->Toevoeging;
            $completedOrder->save();

            $i = 0;
            foreach($payment->metadata->cow as $offerRows)
            {
                $koe = koeien::find($payment->metadata->cow[$i]);
                $koe->aantalverkocht = $koe->aantalverkocht + $payment->metadata->quantity[$i];
                $koe->save();

                $orderID = orders::where('MollieID', $paymentId)->get();
                $bestellingID = 0;
                foreach ($orderID as $idOrder){
                    $bestellingID = $idOrder->OrderID;
                }
                $orderRow = new orderRows;
                $orderRow->OrderID = $bestellingID;
                $orderRow->KoeID = $payment->metadata->cow[$i];
                $orderRow->Aantal = $payment->metadata->quantity[$i];
                $orderRow->save();
                $i++;
            }
        }
        else{
            $completedOrder = new orders;
            $completedOrder->MollieID = $paymentId;
            $completedOrder->MollieID = $paymentId;
            $completedOrder->Klantnummer = $payment->metadata->customerid;
            $completedOrder->Datum = $payment->metadata->datum;
            $completedOrder->Betaald = 0;
            $completedOrder->Bedrag = $payment->metadata->bedrag;
            $completedOrder->save();
        }
    }

**Comment by Jubeki** [comment]
Better formatted:
```php
public function handle(Request $request) {

    $paymentId = $request->input('id');
    $payment = Mollie::api()->payments->get($paymentId);

    if ($payment->isPaid()) {

        $completedOrder = new orders;
        $completedOrder->MollieID = $paymentId;
        $completedOrder->Klantnummer = $payment->metadata->customerid;
        $completedOrder->Datum = $payment->metadata->datum;
        $completedOrder->Betaald = 1;
        $completedOrder->Bedrag = $payment->metadata->bedrag;
        $completedOrder->Postcode = $payment->metadata->Postcode;
        $completedOrder->Plaats = $payment->metadata->Plaats;
        $completedOrder->Straat = $payment->metadata->Straat;
        $completedOrder->Huisnummer = $payment->metadata->Huisnummer;
        $completedOrder->Toevoeging = $payment->metadata->Toevoeging;
        $completedOrder->save();
    
        $i = 0;
        foreach($payment->metadata->cow as $offerRows) {

            $koe = koeien::find($payment->metadata->cow[$i]);
            $koe->aantalverkocht = $koe->aantalverkocht + $payment->metadata->quantity[$i];
            $koe->save();

            $orderID = orders::where('MollieID', $paymentId)->get();
            $bestellingID = 0;

            foreach ($orderID as $idOrder) {
                $bestellingID = $idOrder->OrderID;
            }

            $orderRow = new orderRows;
            $orderRow->OrderID = $bestellingID;
            $orderRow->KoeID = $payment->metadata->cow[$i];
            $orderRow->Aantal = $payment->metadata->quantity[$i];
            $orderRow->save();
            $i++;
        }

    } else {
        $completedOrder = new orders;
        $completedOrder->MollieID = $paymentId;
        $completedOrder->MollieID = $paymentId;
        $completedOrder->Klantnummer = $payment->metadata->customerid;
        $completedOrder->Datum = $payment->metadata->datum;
        $completedOrder->Betaald = 0;
        $completedOrder->Bedrag = $payment->metadata->bedrag;
        $completedOrder->save();
    }
}
```

**Comment by XavegX367** [comment]
Wow, I don't know what things are changed. But it certainly did fix the error! Could you tell me what I did wrong? I am still a student and really want to learn from it. Appreciate it!

**Comment by Jubeki** [comment]
I just want to say that I didn't change any code. I only formatted it.

So I don't know from where the issue comes.

But here some general advice:
Read this of the mollie docs: https://docs.mollie.com/payments/accepting-payments

1. When the customer goes to the checkout you already create a order and associate it with the payment ID which you get from mollie.
2. The Customer completes the checkout and you receive a webhook from mollie
3. The Webhook contains the Payment ID.

Then with
```php
$order = orders::where('MollieID', $paymentId)->firstOrFail();
```
you can get the order which the customer placed. No need to use metadata from mollie for this.

You can check the status of the payment with `$payment->isPaid()` for example.
And the update the order accordingly.

**Comment by Jubeki** [comment]
If you don't want to handle all the payment stuff yourself it would also maybe worth it to work with Laravel Cashier Mollie.
https://www.cashiermollie.com/04-charges.html

This is usefull if you expect multiple payments from the same customer.

If you only want single charges like you currently do I recommend using the current package.

**Comment by XavegX367** [comment]
Thank you very much, I will look into it!
