### ISSUE TITLE
How to access a payments metadata in the webhook

### ISSUE THREAD

**Issue by daan3011** [mollie/laravel-mollie#189]
I'm trying to access an orders metadata in the webhook so I can associate the payment with the right order in the database, I had hoped to find it by looking at the code of the api wrapper but no luck so far. The most logical way seemed $payment->metadata but that doesn't work. Any help would be appreciated. I'm using Laravel 8 and the latest version of Laravel Mollie

**Comment by turpoint** [comment]
It should be `$payment->metadata`. For example:
```
$payment = Mollie::api()->payments->get($paymentId);
$invoice = Invoice::find($payment->metadata->invoice_id)->first();
```

**Comment by sandervanhooft** [comment]
@turpoint is correct. If it's not there it wasn't stored properly during creation/update.
