### ISSUE TITLE
Adding getClient() method

### ISSUE THREAD

**Issue by juukie** [mollie/laravel-mollie#19]
I guess it would be handy to add this method to get the client in case someone might want to interact with it directly:

```
public method getClient()
{
    return $this->client;
}
```

Let me hear your thoughts!

**Comment by FaaPz** [comment]
@juukie Our Laravel package is merely a wrapper for our [Mollie API client for PHP](https://github.com/mollie/mollie-api-php). All relevant methods are already inherited.

What do you think, @robin-mollie?

**Comment by robin-mollie** [comment]
@juukie Building on what @FaaPz said, all relevant client endpoints are available through the methods on the wrapper, and this is our preferred way of accessing those. :)

**Comment by juukie** [comment]
Ok thanks for reply.
