### ISSUE TITLE
[2022-04-19T12:31:50+0000] Error executing API call (422: Unprocessable Entity): Your account is currently suspended. Documentation: https://docs.mollie.com/overview/handling-errors

### ISSUE THREAD

**Issue by Fahadi30** [mollie/laravel-mollie#190]
showing this error .

**Comment by Jubeki** [comment]
Please contact the mollie support for more information or take a look at your mollie dashboard. Like the error says: It seems your account is currently suspended and you need to take some kind of action to activate the account again.
