### ISSUE TITLE
Possibility to get mobileAppCheckout URL?

### ISSUE THREAD

**Issue by ArondeParon** [mollie/laravel-mollie#191]
## Expected Behavior
As per the documentation, it should be possible to retrieve a `mobileAppCheckout` URL for some payment providers, but I don't see this reflected in the SDK. 

## Current Behavior
There is a `getCheckoutUrl()` that returns the checkout URL for the response.

I would expect `getMobileCheckoutUrl()` as well, but it seems to be missing.

## Considerations

I am not entirely sure when and where the `mobileCheckoutUrl` is included in the response. I have not seen it so far, but it would be great if I can stick as close the documentation as possible.

**Comment by sandervanhooft** [comment]
Good catch @ArondeParon !

Working on a patch here: https://github.com/mollie/mollie-api-php/pull/621
