### ISSUE TITLE
FatalErrorException in MollieServiceProvider.php

### ISSUE THREAD

**Issue by nickyadvokaat** [mollie/laravel-mollie#2]
Hi,

I'm getting the following error when making a call to Mollie:
```
FatalErrorException in MollieServiceProvider.php line 101:
Class 'Mollie\Laravel\MollieApiWrapper' not found
```
I have followed the instructions and have:
- Required and installed `laravel/socialite` and `mollie`
- Added providers and aliases to `config/app.php`
- Created ` config/mollie.php` and added to `config/services.php`
- Added keys to `.env` file
- `use Mollie;` in my class
- I also did a `php artisan optimise` and `composer dump-autoload`

Thanks!

**Comment by FaaPz** [comment]
Thank you for reporting this bug. We've just released a patch:
https://github.com/mollie/laravel-mollie/releases/tag/1.1.1 (a9b52868af55eb638c2d2dc92ecd362bcbac694d)

**Comment by ruteeb** [comment]
hello dear, how can use this patch? I found jsu folder
