### ISSUE TITLE
Laravel HTTP client 

### ISSUE THREAD

**Issue by Skullbock** [mollie/laravel-mollie#201]
I've written for my project a ` MollieLaravelHttpClientAdapter` that implements `MollieHttpAdapterInterface` and was wondering if it would make sense to PR it here, and have the ServiceProvider use this new client adapter to make the API calls.

It's useful to me because i can then make use of the `Http::fake` functionality that Laravel provides to fake outgoing calls to Mollie in my tests.

Alongside this, i also have a `Mollie::fake()` implementation nearly ready to avoid having to test Mollie in integration every time, while retaining the core functionalities

Thanks!

**Comment by sandervanhooft** [comment]
Sounds cool, happy to review it!

**Comment by Treggats** [comment]
@sandervanhooft can this be included in a new release?

**Comment by Treggats** [comment]
🙏  Thank you 😄
