### ISSUE TITLE
symfony/finder dependency locked to 6.0

### ISSUE THREAD

**Issue by tomcoonen** [mollie/laravel-mollie#204]
Is it intentional that the `symfony/finder` version is locked to 6.0 instead of ^6.0 in v2.19.2?
This blocks using `symfony/finder` 6.1 in a project.

**Comment by sandervanhooft** [comment]
Hi @tomcoonen ,

Good catch. Yes, there recently was an issue with Symfony's Finder, therefore the dependency constraint was patched in. We'll investigate the current situation to see if we can expand or remove the current constraint.

Cc @ciungulete

**Comment by ciungulete** [comment]
We lock it currently for 6.0 because `symfony/finder` requires  `"php": ">=8.1"`

**Comment by tomcoonen** [comment]
@ciungulete Then you can still use '^6.0' in this package since composer won't install 6.1 when you don't have PHP 8.1.

**Comment by sandervanhooft** [comment]
Looks like it's used by `php-cs-fixer` and `testbench`, so we can also try moving it to the list of dev dependencies.

**Comment by ciungulete** [comment]
Is fixed now

**Comment by tomcoonen** [comment]
Great, thanks guys!
