### ISSUE TITLE
Customers update

### ISSUE THREAD

**Issue by RobertArissen** [mollie/laravel-mollie#21]
Hoi,

Ten eerste bedankt voor het maken van deze package werkt super!

Ik mis alleen een klein ding: Het update van een customer object.

Misschien een idee om het zo te maken:

$customer = Mollie::api()->customer()->get(ID);

$customer->name = 'New Name';
$customer->save();

Zou voor mij erg handig zijn!

**Comment by Thijs-Riezebeek** [comment]
Beste Robert,

Dit komt doordat de laravel-mollie module gebouwd is op onze php-api-client en die ondersteunt op dit moment nog geen update voor een customer object.

Bedankt dat je ons alert gemaakt hebt op dit probleem. We gaan er snel verandering in brengen en verwachten binnen 1-2 dagen de php-api-client te hebben bijgewerkt.

Als de wijziging is doorgevoerd dan zal je `composer update` moeten draaien om de nieuwe php-api-client te gebruiken en dan zal het zeer waarschijnlijk als volgt werken:

```php
$customer = Mollie::api()->customer()->get(ID);

$customer->name = 'New Name';

Mollie::api()->customer->update($customer);
```

Ik hoop je hiermee voldoende te hebben geinformeerd.

Met vriendelijke groet,
Thijs Riezebeek

**Comment by Thijs-Riezebeek** [comment]
Beste Robert,

De Mollie php-api-client module heeft zojuist versie 1.7.0 uitgebracht. In deze release zit het updaten van een customer object.

Als je composer update draait in je laravel project dan zou de nieuwe versie van de php-api-client gedownload moeten worden, waarna je op de manier die ik in mijn vorige reactie aangaf een customer object kan updaten.

Met vriendelijke groet,
Thijs Riezebeek
