### ISSUE TITLE
API KEY only in env ?

### ISSUE THREAD

**Issue by matthieugluszkowski** [mollie/laravel-mollie#210]
Hello, 
I am sorry but it's not an issue. It's a question.
I am doing Mollie integration through this package but I have a use case that is blocking me. 
I don't have only one API KEY, I have a network of 400 shops which each have their API KEY. This is why at the time of payment I retrieve the API KEY of the store in question by an other secure webservice before proceeding to payment. 
How can I use the API KEY from the secure webservice return and not with the env file?

Thank you in advance !

Have a nice day,

Matthieu

**Comment by sandervanhooft** [comment]
Hi @matthieugluszkowski,

It is highly recommended to use Mollie Connect for this (OAuth).

If you really want to stick to using the keys, it's probably easier to use mollie/mollie-api-php directly instead of this wrapper package.
