### ISSUE TITLE
Webhook failed with status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Dynalogical** [mollie/laravel-mollie#211]
Ik heb deze package toegevoegd aan mijn Laravel applicatie en werkt op zich naar behoren. Het probleem speelt echter op zodra de webhook van mollie contact probeert te krijgen met mijn test server. Ik krijg de melding: Webhook failed with status code 500 (Internal Server Error). Het gekke is dat het in mijn andere applicaties wel gewoon naar behoren werken met dezelfde code.

Composer.json
`"mollie/laravel-mollie": "^2.0",`

Ik heb onderstaande toegevoegd aan mijn `VerifyCSRFToken.php`
`'webhooks/mollie'`

Route:
`Route::post('webhooks/mollie', [\App\Http\Controllers\ApiController::class, 'GetMollieStatus'])->name('webhooks.mollie');`

Functie:
```
    public function GetMollieStatus(Request $request) {
        $paymentId = $request->input('id');
        $payment = Mollie::api()->payments->get($paymentId);

        if ($payment->isPaid())
        {
            echo 'Payment received.';
            // Do your thing ...
        }
    }
```

Ik krijg hoe dan ook de melding 500 en ik weet inmiddels niet meer waar ik het moet zoeken. Het test domein is een HTTP domein waar SSL niet actief is. Zou dat onderdeel van het probleem kunnen zijn?

edit: Ik krijg ook geen enkele vorm van logging terug binnen mijn Laravel applicatie.

**Comment by TVBZ** [comment]
Were you able to solve this?
