### ISSUE TITLE
Latest 2.20.0 causes 415 error, fixed by downgrading to 2.19.2

### ISSUE THREAD

**Issue by basepack** [mollie/laravel-mollie#212]
## Current Behavior
Cannot do an API call via `Mollie::api()->payments()->create([ your data ]);`

## Possible Solution
Downgrade to 2.19.2 works immediately.

## Steps to Reproduce (for bugs)
Upgrade to 2.20.0 and call the Payments API.

## Context
Full error: 
```
Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/overview/handling-errors
```

**Comment by RamonSmit** [comment]
I second this, had the same issue. Already had a phone call with Mollie about this. I think its related to #202.

**Comment by sandervanhooft** [comment]
Hi,

I'll look into this later tonight.

If possible, can you share the actual code you're using so I can reproduce this properly? And confirm that it's throwing the 422 as reported in your ticket description, not a 415 as in the ticket title?

**Comment by sandervanhooft** [comment]
Cc @Skullbock

**Comment by Skullbock** [comment]
@basepack can you test the attached pr #213 ? Seems like it adds a double contentype header that makes mollie go nuts.

**Comment by sandervanhooft** [comment]
@basepack @Skullbock I am reverting to the former http client resolution in the MollieServiceProvider for now so I can get some sleep tonight :) . Will investigate later this week, including the proposed PR #213.

Thanks for reporting and helping out everyone, much appreciated.

**Comment by sandervanhooft** [comment]
https://github.com/mollie/laravel-mollie/releases/tag/v2.20.1

**Comment by sandervanhooft** [comment]
All good now!

[v2.20.2 release notes](https://github.com/mollie/laravel-mollie/releases/tag/v2.20.2)
