### ISSUE TITLE
Update access token from refresh token

### ISSUE THREAD

**Issue by gtapps** [mollie/laravel-mollie#22]
Hey guys,

I needed to update the access token from the access token so I created the following code on MollieConnectServiceProvider.php:

    public function getRefreshTokenResponse($code)
    {
        $response = $this->getHttpClient()->post($this->getTokenUrl(), [
            'headers' => ['Accept' => 'application/json'],
            'form_params' => $this->getRefreshTokenFields($code),
        ]);
        return json_decode($response->getBody(), true);
    }

    public function getRefreshTokenFields($code)
    {
        
        return [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret,
            'code' => $code,
            'grant_type' => 'refresh_token',
            'refresh_token' => $code,
        ];
    }

Now to get a new access token we can easily call the following:
 $result = Socialite::with('mollie')
                ->scopes($scopes)
                ->getRefreshTokenResponse($refreshToken);

**Comment by FaaPz** [comment]
We've just released **v1.5.0** (5ec1394fed5da31064f73421c0621be093b1eee6)! 😄
