### ISSUE TITLE
Feature request: Variable API key

### ISSUE THREAD

**Issue by TVBZ** [mollie/laravel-mollie#224]
## Expected Behavior
I would love to be able to set the api key from within the controller. 

## Current Behavior
API key is set in .env file.

## Context
I'm using mollie in a multidomain setup with 1 admin panel. For the mollie api key to work, I need to use different keys for different domains. I have a db table with brands, each brand having it's own domain, logo, etc. The api key could be a column in that table. 

Something like ```mollie()->setApiKey($brand->api_key);``` would do the trick. The API key in .env file could be used as default.

**Comment by TVBZ** [comment]
I missed it. That exact function is allready there. 😄  Thank you!

**Comment by sandervanhooft** [comment]
NP, enjoy!
