### ISSUE TITLE
Mandate creation error

### ISSUE THREAD

**Issue by AlphaNimmi** [mollie/laravel-mollie#230]
```php
    $mandate = $customer->createMandate([
        "method" => \Mollie\Api\Types\MandateMethod::DIRECTDEBIT,
        "consumerAccount" => 'NL34ABNA0243341423',
        "consumerName" => 'B. A. Example',
    ]);

  $subscription = $customer->createSubscription([
                "amount" => [
                    "value" => $price_to_charge_formatted, 
                    "currency" =>  $_ENV["CURRENCY"],
                ],
                "times" => 12,
                "interval" => $interval,
                "description" => "Subscription ",
                'webhookUrl' => site_url('mollie_webhook') ,
                "metadata" => [
                    'user_id' => $user_id,
                    'plan_id_id' => $plan_id_id,
                    'care_type' => $care_type
                ],
            ]);
```

Create mandate like this and subscription.But its showing Subscriptions as active and and Transactions as pending 

Description                  Subscription
Amount                         €79.99
Payment ID                 tr_oZwhgYghLG
Status                              PENDING
Customer reference          [cst_2ySjDSMcBW](https://my.mollie.com/dashboard/org_17504178/customers/cst_2ySjDSMcBW)
Subscription reference        sub_8SUFZhdrug
Mode                               test
Created at                           6 July 2023 at 22:20
Webhook URL                         https://wealthyplaymates.com/mollie_webhook
SEPA                                     Direct Debit
Amount                                      €79.99
Transfer reference                   SD11-1036-0707-6929
Creditor identifier                       NL08ZZZ502057730000
Consumer name                       nimmmi
IBAN                            NL34ABNA0243341423

Due date                              10 July 2023
Signature date                             6 July 2023

When i contact with customer care they told Because you can’t test SEPA Direct Debit recurring payments. Since we never receive an actual payment which triggers the paid status with Sepa Direct Debit.
I would rather advise you to test Creditcard recurring payments since it is the same testing flow.

**Comment by sandervanhooft** [comment]
Hi,

Thanks for opening this ticket. 

In order for me to help you better: What is your question here?

**Comment by AlphaNimmi** [comment]
Create mandate like this and subscription.But its showing Subscriptions as active and and Transactions as pending
Why transactions are pending

**Comment by AlphaNimmi** [comment]
I used changePaymentState for testing recuuring payments.But showing error changePaymentState() method is not available in the PaymentEndpoint

**Comment by AlphaNimmi** [comment]
https://github.com/laravel/cashier-mollie/issues/169  I found the solution from here

**Comment by AlphaNimmi** [comment]
![Screenshot 2023-07-10 125218](https://github.com/mollie/laravel-mollie/assets/138252879/136b3999-6bf6-4912-95f8-1f4a2a3ca6b2)Here Subscription created at 12.38.ANd subscription charged at 12.50.Ony after subscription charged I can get the changePaymentState

 $url = "https://api.mollie.com/v2/customers/$customerId/subscriptions/$subscriptionId/payments";
            $headers = [
                "Authorization: Bearer $api_key",
            ];
            
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            
            $response = curl_exec($ch);
            if ($response === false) {
                $error = curl_error($ch);
                echo "cURL Error: $error";
            } else {
                $result = json_decode($response, true);
                // Process the result as needed
                var_dump($result);
            }
            
            curl_close($ch);
            $response = json_decode($response, true);
            $changePaymentStateUrl = $response['_embedded']['payments'][0]['_links']['changePaymentState']['href'];
            echo "Change Payment State URL: $changePaymentStateUrl";

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
