### ISSUE TITLE
I am unable to create first payment for customer created

### ISSUE THREAD

**Issue by kirti-u** [mollie/laravel-mollie#232]
Hello,
I have implemented the this for my laravel project. This is working for regular payment. but not working when i created it for 'first payment' for the customer i created.
I have successfully created customer using following:
> $customer = Mollie::api()->customers->create([
         'name'  => $user->full_name,
          'email' => $user->email,
> ]);

$order_no = 'ABC';
$mollie_customer_id = $customer->id;
but getting error on following code:
> $payment = Mollie::api()->payments()->create([
                    'amount' => [
                        'currency' => 'EUR',
                        'value'    => '25.00',
                    ],
                    'customerId'   => $mollie_customer_id,
                    'sequenceType' => 'first',
                    'description'  => 'My Initial Payment',
                    'redirectUrl'  => route('orders.payment', ['locale'=>getLocale(), 'order_no'=>$order_no]),
                    'webhookUrl'   => route('orders.mollie_webhook'),
 > ]);
![customer_first_payment](https://github.com/mollie/laravel-mollie/assets/21682085/c56dcf75-fcba-44cb-9267-3df3d3736dc6)

I have attached the screenshot of error also.
when i comment 'webhookUrl' line, it gives error on 'redirectUrl' and so on.
can somebody help please?

Thanks.

**Comment by sandervanhooft** [comment]
Hi,

Can you double check that:

- you have enabled payment methods eligible for first payments on the Mollie dashboard (i.e. creditcard or ideal)
- these payment methods are corresponding to the profile you're authenticating with

Payment methods pending review cannot be used in production, however these are immediately available in test mode once switched on in the dashboard.

**Comment by kirti-u** [comment]
Thanks for reply.
This is test mode i am working on.
Only iDEAL payment method is enabled.
I have just enabled 'Cards' and now it is working!
