### ISSUE TITLE
Laravel 11.0, PHP 8.3 not supported

### ISSUE THREAD

**Issue by DevelopmentNightmare** [mollie/laravel-mollie#239]
Installing mollie/laravel in a new Laravel 11 project results in the following error(s):

Configuration:
Laravel 11
PHP 8.3

Problem 1
    - mollie/laravel-mollie[1.0.0, ..., 1.1.3] require illuminate/contracts 5.0.*|5.1.*|5.2.* -> found illuminate/contracts[v5.0.0, ..., v5.2.45] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie[1.2.0, ..., v1.5.1] require php ^5.5.9 || ^7.0 -> your php version (8.3.3) does not satisfy that requirement.
    - mollie/laravel-mollie[v2.0.0, ..., v2.6.0] require illuminate/support ^5.5 -> found illuminate/support[v5.5.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie v2.7.0 requires illuminate/support ^5.5|^6.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie[v2.7.1, ..., v2.10.0] require php ^7.1.3|^7.2 -> your php version (8.3.3) does not satisfy that requirement.
    - mollie/laravel-mollie[v2.11.0, ..., v2.12.0] require php ^7.2 -> your php version (8.3.3) does not satisfy that requirement.
    - mollie/laravel-mollie[v2.13.0, ..., v2.17.0] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie[v2.18.0, ..., v2.21.1] require illuminate/support ^8.0|^9.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie[v2.22.0, ..., v2.25.0] require illuminate/support ^9.0|^10.0 -> found illuminate/support[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.
    - mollie/laravel-mollie v2.24.0 requires mollie/mollie-api-php v2.58.0-beta -> found mollie/mollie-api-php[v2.58.0-beta] but it does not match your minimum-stability.
    - Root composer.json requires mollie/laravel-mollie * -> satisfiable by mollie/laravel-mollie[1.0.0, ..., v1.5.1, v2.0.0, ..., v2.25.0].

**Comment by sandervanhooft** [comment]
Related: https://github.com/mollie/laravel-mollie/pull/238

**Comment by Naoray** [comment]
closed with #238
