### ISSUE TITLE
Retry failed payments via mollie checkout

### ISSUE THREAD

**Issue by ignaciocunado** [mollie/laravel-mollie#243]
## Expected Behavior

When a payment fails, the mandate is automatically canceled. It would be nice if users could retry the failed payment via the checkout page, and, for example change their payment method.

## Current Behavior

Currently, there exists no way for users to go through the checkout to retry a failed payment.

## Possible Solution

A possible solution could be to add a method which redirects the user to the checkout page, and pays for the failed order.

## Context

Sometimes our users' banks reject the payment multiple times, and it would be easier for them and for us to retry payments via the checkout.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sandervanhooft** [comment]
Hi @ignaciocunado,

Thanks for reaching out!

Your request goes beyond the scope of this package.

However, if you're looking for inspiration to implement it on your end (which is definitely possible): The [Mollie Laravel Cashier](https://github.com/mollie/laravel-cashier-mollie) package offers some help in dealing with the use cases you're describing (i.e. retries).

Also feel free to jump on the Mollie Discord if there are any feature requests you'd like to share. See you there?
