### ISSUE TITLE
Test environment not displaying errors after selecting a failed purchase state

### ISSUE THREAD

**Issue by ricardoappx** [mollie/laravel-mollie#244]
I've set up a test environment for mollie payments on a test server. Simulating a payment while setting the state to paid works fine, but when selecting the the failed state (including the forced card errors with the tabled magical amounts) there's no error displayed.

## Expected Behavior
When a payment fails, an error message should be displayed with the reason why the payment failed, with and without magical amounts.

## Current Behavior
When following through with the failed payment, it redirects to the select-method page with no errors displayed. In the mollie dashboard with test mode enabled, the failed payments also don't register.

## Your Environment
* Version used: 3.0.0
* Environment name and version: PHP 8.2, Laravel 11
* Operating System and version: macOS 14.2.1 (23C71)

**Comment by Naoray** [comment]
Hi @ricardoappx,

Can you share the steps to reproduce this error? A code snippet would be great to pinpoint the issue. Thanks!

**Comment by sandervanhooft** [comment]
Closing this for now, let me know if it should be reopened.
