### ISSUE TITLE
Composer tells me to remove laravel/framework

### ISSUE THREAD

**Issue by danielgelling** [mollie/laravel-mollie#25]
## Expected Behavior
mollie/laravel-mollie should just install to the vendor directory.

## Current Behavior
When running `composer require mollie/laravel-mollie` composer says the following (shortened message):

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mollie/laravel-mollie ^1.3 -> satisfiable by mollie/laravel-mollie[1.3.0].
    - Conclusion: remove laravel/framework v5.4.3
    - Conclusion: don't install laravel/framework v5.4.3

## Steps to Reproduce (for bugs)

1. Create a new Laravel project
2. Run `composer require mollie/laravel-mollie`

**Comment by robin-mollie** [comment]
Thanks for notifying us!

We've fixed the release (currently on 1.4.1), running `composer require mollie/laravel-mollie` again should work.
