### ISSUE TITLE
Create profile with methods

### ISSUE THREAD

**Issue by sweebee** [mollie/laravel-mollie#28]
I'm using Mollie Connect to create a profile. But is there an option to activate some pay methods as well?

**Comment by willemstuursma** [comment]
Sorry for the long delay. We are going to move this issue to our roadmap.

**Comment by jimkaler** [comment]
@willemstuursma  what is the payment parameter for SEPA Direct debit?
Like for iDeal its 'ideal'.

**Comment by sandervanhooft** [comment]
Hi @jimkaler ,

You're probably looking for `directdebit` ([docs](https://docs.mollie.com/reference/v1/payments-api/create-payment)). Also mind [this note](https://docs.mollie.com/reference/v1/payments-api/create-payment#sepa-direct-debit).

Please open a new issue if this does not answer your question, as it is slightly off-topic here.

**Comment by sandervanhooft** [comment]
> Sorry for the long delay. We are going to move this issue to our roadmap.

@willemstuursma Should we keep this open (here)?

**Comment by willemstuursma** [comment]
No.
