### ISSUE TITLE
Retreiving ID 

### ISSUE THREAD

**Issue by riksnelders** [mollie/laravel-mollie#36]
How would i retrieve the payment ID after redirect? Without using  a database to store it..

**Comment by ndijkstra** [comment]
Hi! You can use our Webhook, to receive a call when the status of the payment has changed. We do a POST request to your webhookUrl, with "id" as POST-data. This id is the Payment ID. (see this [example](https://github.com/mollie/mollie-api-php/blob/master/examples/02-webhook-verification.php))
In the redirectUrl you can place your own unique number, like an order number to receive the status of that order.

See also this guide: https://www.mollie.com/nl/docs/webhook
