### ISSUE TITLE
The optional parameter 'dueDate'-not working correctly by creating a payment

### ISSUE THREAD

**Issue by nickurt** [mollie/laravel-mollie#38]
Hello,

I discovered a problem with the dueDate-parameter by creating a [payment](https://www.mollie.com/en/docs/reference/payments/create#parameters-banktransfer) ...

```php
$mollie = \Mollie::api();
$mollie->setAccessToken('qwertyuiop');

$payment = $mollie->payments()->create([
	//

	'dueDate' => Carbon::now()->addDays(4)->format("Y-m-d"),
	
	'metadata' => [
		'order_id' => $payment->id,
	]
]);
```

Based on this example (without specify the method-parameter, so optional parameters should be applied when the consumer selects the relevant payment method), the dueDate should be 2018-02-24 (payment was created on 2018-01-20), but I got 2018-03-05 after the payment was created. 

So, the consumer got a ~14d period to pay instead of the given ~4d period.

What is the problem here?, and how can I solve it?

### Versions

"name": "mollie/laravel-mollie",
"version": "v1.5.1",

"name": "mollie/mollie-api-php",
"version": "v1.9.4",

Thanks

**Comment by willemstuursma** [comment]
Hi @nickurt. This is a bug on our end. Due to some constraints the `dueDate` is one of the few parameters that is not forwarded. If you want to use it, you must create a `banktransfer` payment directly.

It's on our roadmap to fix this, unfortunately I can't give you a date.
