### ISSUE TITLE
Checkout doesn't show

### ISSUE THREAD

**Issue by Raynth** [mollie/laravel-mollie#39]
I've installed en configurated as shown in the README.md. I tested with this example:

$payment = Mollie::api()->payments()->create([
    "amount"      => 10.00,
    "description" => "My first API payment",
    "redirectUrl" => "https://webshop.example.org/order/12345/",
]);

$payment = Mollie::api()->payments()->get($payment->id);

if ($payment->isPaid())
{
    echo "Payment received.";
}

I don't see the checkout, I'm getting no errors. I see the transaction showing in my account with the status 'open' at www.mollie.com. I use Chrome 65 and Laravel 5.6. I tried Edge also.

The documentation is poor for beginners. I'll need some help.

**Comment by willemstuursma** [comment]
This package does not provide a "checkout", as it does not integrate with any ecommerce solutions. Instead, is it just a convenience wrapper for Laravel for the `mollie/mollie-api-php` package. 

Have a look at our other package for drop in plugins for ecommerce software.

**Comment by cannect** [comment]
There is actually a function to get the Checkout Url after you create the payment: `$payment->getCheckoutUrl()`
