### ISSUE TITLE
Build against nightly

### ISSUE THREAD

**Issue by willemstuursma** [mollie/laravel-mollie#51]
It would be great if you could also build against PHP 7.3 (`nightly`).

Optionally, you could allow this build to fail.

Sidenote: I'm not sure about `--prefer-source`, this will require composer to clone all the dependencies instead of just getting the zip files. Its more for developing on the dependencies.

**Comment by sandervanhooft** [comment]
Thanks @willemstuursma 
I'll look into `PHP 7.3 (nightly)` support.

About `--prefer-source`: I'm giving `--prefer-dist` a try right now.

**Comment by sandervanhooft** [comment]
- `--prefer-dist` is performing slightly better on Travis.
- `nightly` builds take about 30 minutes. `--prefer-lowest` times out. Without that flag it succeeds, but just before timing out.
- Also tried running `hhvm`, times out unfortunately. Will drop `hhvm` for now.

**Comment by willemstuursma** [comment]
`hhvm` support is generally dropped by many libraries, we can do without.

To me, `--prefer-lowest` is not really necessary. 

Dropping the sudo requirement will move you to a faster container based infra at travis.

**Comment by sandervanhooft** [comment]
I'll drop `hhvm` and `prefer-lowest` then.

The `sudo: required` was actually suggested by Travis support, because it would trigger the use of a higher RAM container (7.5GB instead of 4GB)...

**Comment by willemstuursma** [comment]
It's probably that the `--prefer-lowest` calculation is very slow / memory intensive.

**Comment by sandervanhooft** [comment]
Worked like a charm!

**Comment by sandervanhooft** [comment]
Worked like a charm - [but only on my fork](https://travis-ci.org/sandervanhooft/laravel-mollie/builds/399948095). I hope Travis support will get back to me to deal with this discrepancy.

**Comment by willemstuursma** [comment]
Figured it out. The `minimum-stability: dev` in `composer.json` was causing Composer to look at too many versions.
