### ISSUE TITLE
Include example to redirect user to checkout screen

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/laravel-mollie#56]
## Expected Behavior

A simple example in the docs describing how to redirect a user to Mollie's checkout screen. Only for default and first/mandate payments.

## Current Behavior

Current payment examples do not include this.

**Comment by willemstuursma** [comment]
Make sure to use HTTP 303 for the redirect so that the checkoutUrl is always accessed with GET.

**Comment by sandervanhooft** [comment]
@willemstuursma Nice addition, as Laravel's `redirect(...)` helper sets it to 302 by default.

(It does always enforce a GET request though.)

```php
function redirect(
    $to = null,
    $status = 302,
    $headers = [],
    $secure = null
);
```

**Comment by sandervanhooft** [comment]
So it will be something like `return redirect($payment->getCheckoutUrl(), 303);'
