### ISSUE TITLE
"The redirect URI provided is missing or does not match"

### ISSUE THREAD

**Issue by renege** [mollie/laravel-mollie#6]
Hello,

I got this: "The redirect URI provided is missing or does not match" on my local environment.

In my .env I have:
```MOLLIE_REDIRECT_URI=http://project123.local/mollie/callback ```

In the settings I have https://livedomain.com/mollie/callback, but I'm testing it all on my local machine that has an invalid TLD of course and can't have httpS what's needed?

**Comment by FaaPz** [comment]
Hi @renege, I suggest you temporarily change the *Redirect URL* in your settings to match the (development) `MOLLIE_REDIRECT_URI` in you `.env` file, so you can at least continue to develop and test.

And yes, we require HTTPS for *Redirect URLs*. If that's not possible on your local environment, then you unfortunately have to click through the browser's SSL warning.

**Comment by renege** [comment]
Yea, but on my local machine Homestead I can't get https to work obviously.

**Comment by FaaPz** [comment]
We only require the *Redirect URL* to contain `https://...` to enforce the secure connection for sending the auth code and such, even though the certificate is not signed, like on development/test environments.

Also, this might help set up SSL on Homestead: https://gist.github.com/cluppi/6792ca8b802d26919045

**Comment by FaaPz** [comment]
Closed due inactivity.
