### ISSUE TITLE
Preparing Laravel-Mollie v3

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/laravel-mollie#76]
This issue is for discussing / listing v3 features.

These features are intended to be included:
- [ ] MIT license (replaces BSD-2)
- [ ] resolve socialite binding issues (probably a breaking change) by using a dedicated MollieConnectServiceProvider.
- [ ] provide default webhook route with controller and events. All configurable.

Also, don't forget:
- [ ] migration guide (if required)
- [ ] update roadmap

**Comment by Wulfheart** [comment]
What is the status of this?

**Comment by sandervanhooft** [comment]
Unchanged. The current v2 is doing fine

**Comment by joostvanhoof** [comment]
Any plans on events instead of webhooks and a Nova package? Would love to use both!

**Comment by sandervanhooft** [comment]
There is a community webhook package.

This package will remain a wrapper around mollie-api-php. For more bells and whistles, I am working on laravel/cashier-mollie v2 (TBA).

**Comment by sandervanhooft** [comment]
Released a while ago. Official Cashier Mollie docs are [here](https://cashiermollie.com).
