### ISSUE TITLE
Get all recent payments: not working in V2

### ISSUE THREAD

**Issue by Datalink-Wouter** [mollie/laravel-mollie#84]
In V1 you could do something like this to list all recent payments.
`$payments = Mollie::api()->payments()->all(0, 100);`

Since V2 the all() method is not there anymore.
Is there another way to access the latest transactions?
(all payments in the last 5 minutes would be even better)

There is a "payments"-endpoint in the main API => https://docs.mollie.com/reference/v2/payments-api/list-payments
but I don't think we can hit the endpoint with this package.

Thanks in advance!

## My environment
* Version used: 2.4.0
* Laravel: 5.7

**Comment by Datalink-Wouter** [comment]
Oops, I guess we should use something like this now:
`Mollie::api()->payments()->page();`

(I think it's helpful to mention this in the documentation too)

**Comment by sandervanhooft** [comment]
Hi @Datalink-Wouter !

Glad to read you found the solution 😊. If you'd like you can further shorten it by using

```php
$payments = mollie()->payments()->page();
```

Thanks for the docs suggestion.
I'm trying to keep the docs a bit condensed here. The case you mentioned is in line with this + docs at https://docs.mollie.com. Let me know if you disagree or need further support.

I'm closing this issue for now.
