### ISSUE TITLE
How to couple a download to a payment

### ISSUE THREAD

**Issue by sjorsvanheuveln** [mollie/laravel-mollie#85]
How would I couple a download after a payment is done? What is the recommended way to this. Add in the webhook, after payment is completed?

**Comment by sandervanhooft** [comment]
Hi @sjorsvanheuveln,

You are on the right track. Once the webhook is called for a payment, check that the payment has status `paid`. You can then offer the download (make sure the file is not publicly accessible, authenticated download only).

**Comment by sjorsvanheuveln** [comment]
So it is possible to implement the download action in the webhook? Because I'm now doing it on the return page, but it looks very redundant as I need to check the DB again.

**Comment by sandervanhooft** [comment]
Take a look at [this guide](https://docs.mollie.com/payments/overview). Step 6 (thank you page) is where you offer the download link.

**Comment by sjorsvanheuveln** [comment]
Ok good, so then I did the right thing and I shouldn't do it in the webhook. Ok, dankjewel Sander!
