### ISSUE TITLE
Class 'App\Http\Controllers\Mollie' not found

### ISSUE THREAD

**Issue by GhoSTBG** [mollie/laravel-mollie#86]
I've just installed this cool package, and when I copy/pasted the example it returns error **"Class 'App\Http\Controllers\Mollie' not found"** I'm working on Laravel 5.7 also can you provide better example because I can't understand how it works?

**Comment by sandervanhooft** [comment]
You'll need to implement a controller yourself.

Check out the Mollie docs to get an understanding of their service. [Here's a quick overview](https://docs.mollie.com/payments/overview).

**Comment by sandervanhooft** [comment]
You'll need to implement a controller yourself.

Check out the Mollie docs to get an understanding of their service.

**Comment by GhoSTBG** [comment]
But how can I use the Mollie class?

**Comment by sandervanhooft** [comment]
Import the Mollie facade.

**Comment by sandervanhooft** [comment]
Or use the `mollie()` helper instead

**Comment by GhoSTBG** [comment]
`use Illuminate\Support\Facades\Moolie;` is giving the same error and `mollie()` helper is throwing `"Call to undefined function App\Http\Controllers\mollie()"`
