### ISSUE TITLE
Can't list all payments

### ISSUE THREAD

**Issue by nouce** [mollie/laravel-mollie#87]
Hi,

I am trying to list al the payments, but it doesn't show the payment objects?

I am using the laravel api wrapper.

My code:

```
$payments = Mollie::api()->payments()->page();
dd($payments);
```

My response is (image):
https://drive.google.com/open?id=1SHUt1SxEZ992OxjCDhcD4EwxmJWmUFZL

According to the documentation i need to get a '_embedded' object? Does someone know what i'm doing wrong?

**Comment by nouce** [comment]
<img width="305" alt="schermafbeelding 2019-01-22 om 19 52 48" src="https://user-images.githubusercontent.com/45368779/51560384-a4bee100-1e84-11e9-8753-5532abb23b57.png">

**Comment by sandervanhooft** [comment]
‘dd($payments[0]);’

?

**Comment by nouce** [comment]
yes, that works. Thanks for the help!

**Comment by sandervanhooft** [comment]
NP, enjoy :)
