### ISSUE TITLE
Tests fails with Socialite [DOING]

### ISSUE THREAD

**Issue by ptondereau** [mollie/laravel-mollie#9]
I put an issue here because I'm still investigating on it.

This isn't a BC but this issue should be open to public.

[Travis Report here](https://travis-ci.org/mollie/laravel-mollie/jobs/134968880)

**Comment by RicardoJ** [comment]
Thank you for your issue @ptondereau. I hope you can find the problem behind the test. I tried it locally but that also failed. Maybe we can mock these classes to succeed the tests?

**Comment by ptondereau** [comment]
Don't worry, I ve found a way. I'm on it.

**Comment by ptondereau** [comment]
@RicardoJ see #13

**Comment by RicardoJ** [comment]
Thank you. @FaaPz will review your pull request and merge this when approved.
