### ISSUE TITLE
laravel 5.4

### ISSUE THREAD

**Issue by pjeutr** [mollie/laravel-mollie#90]
Im using laravel/framework v5.4 and it seems to work fine with this framework 
but installing fails because of "illuminate/support": "^5.5",

## Expected Behavior
composer require mollie/laravel-mollie:^2.0
working fine with lower versions of laravel

## Current Behavior
composer require mollie/laravel-mollie:^2.0
Your requirements could not be resolved to an installable set of packages.

## Possible Solution
composer.json:20
"illuminate/support": "^5.3",

## Context

Not sure why laravel 5.5 is required, propably because of auto-discovery
I added MollieServiceProvider and the Mollie alias manually and everything seems to be working fine
or am I forgetting something and will some things not work?

**Comment by sandervanhooft** [comment]
Hi @pjeutr ,

Thanks for writing this ticket.

When this client was upgraded to v2, there were some issues making it impossible to maintain support for Laravel 5.4.

Unfortunately I can't recollect specifically which dependencies were causing these issues - there's a good chance it's possible now.

Feel free to submit a PR with modified `composer.json` and `travis` files.

**Comment by sandervanhooft** [comment]
I'm closing this issue for now, let me know if it should be reopened.

**Comment by pjeutr** [comment]
Just to report back that I found no problems using Laravel 5.4.
Tested with single and recurring payments with a customer.

**Comment by sandervanhooft** [comment]
Thanks for reporting this back @pjeutr, good to know.

During the upgrade of the underlying core mollie php client, we decided to take Laravel's latest LTS (5.5) version as a minimum requirement. I'm sticking to that.
