### ISSUE TITLE
Methods/allAvailable with oAuth: Non-existent body parameter "profileId" for this API call

### ISSUE THREAD

**Issue by nickurt** [mollie/laravel-mollie#93]
It looks like something changed with the Methods/allAvailable-call when you are using this with oAuth/tokens.

Previously (~ 3/4w ago), this worked ...
```php
$allMethods = $mollie->methods()->allAvailable([
  //
]);
```

In a recent commit in the mollie-api-php repo I saw a new mention 'profileId parameter if using OAuth Access Tokens', so I added the 'profileId' parameter, like this ..
```php
$allMethods = $mollie->methods()->allAvailable([
  'profileId' => 'pfl_xxxxxxxxxx'
]);
```
but after that I got this exception thrown

```Error executing API call (422: Unprocessable Entity): Non-existent body parameter "profileId" for this API call.. Field: profileId. Documentation: https://docs.mollie.com/guides/handling-errors```

----

mollie/mollie-api-php: v2.8.2
mollie/laravel-mollie: v2.5.0

**Comment by sandervanhooft** [comment]
Hi Nick,

Thanks for reporting this. You’re correct
We’re aware of this issue and working on a fix in the mollie-api-php package. I’ll report back here when it’s available.

**Comment by nickurt** [comment]
Ah ok, Sander. 

No worries, thanks for your hardwork (as always) :+1:

**Comment by sandervanhooft** [comment]
Related core client issue: https://github.com/mollie/mollie-api-php/issues/375

**Comment by sandervanhooft** [comment]
Hi @nickurt ,

I've released a patch just now. If you run `composer update` or `composer update mollie/mollie-api-php` it should update to the `v2.8.3` php core client.

[Release info here](https://github.com/mollie/mollie-api-php/releases/tag/v2.8.3)

**Comment by nickurt** [comment]
Thank you, Sander, it worked.
