### ISSUE TITLE
Batch refreshing of access tokens

### ISSUE THREAD

**Issue by crnkovic** [mollie/laravel-mollie#94]
Hey folks,

what would be the best way to refresh a Mollie Connect access token for multiple users?

Pretty common use-case: have a webshop where sellers hook up their Mollie account using Socialite. When a purchase is made, make a payment to their account but take an application fee. Currently, all Mollie tokens obtained via Socialite expire an hour after obtaining, and if someone tries to purchase a product that this particular seller sells, the token is expired and the payment can’t go through.

My idea: run a queued job in Laravel every 5 minutes that would loop through sellers whose token expires within 5 minutes and use refresh token to obtain new access token. Is there a better way of doing that?

I feel the docs don’t give enough information about how to do that. I know this repository isn’t related to this particular issue, but this feels like a best place to ask this sort of question.

I was wondering how other developers handle expired tokens.

**Comment by sandervanhooft** [comment]
Hi @crnkovic ,

The Mollie docs mention refreshing the access tokens _periodically_, as you suggest.

Alternatively, you can fetch a new access token when you need it ("lazily").

Both are accepted methods, there is no strict "OAuth way" for this.
