### ISSUE TITLE
Error executing API call (422: Unprocessable Entity): No suitable payment methods found

### ISSUE THREAD

**Issue by rassemdev** [mollie/laravel-mollie#96]
## Expected Behavior
I'm trying to integrate laravel-mollie in my e-commerce website. Though i'm getting an error at the beginning.

## Current Behavior
While checking out from my cart option i'm calling the function that is creating the payment using the code that shown in example. But It is giving me error below.

Mollie \ Api \ Exceptions \ ApiException (422)
Error executing API call (422: Unprocessable Entity): No suitable payment methods found. Documentation: https://docs.mollie.com/guides/handling-errors

I'm not getting what is causing the problem. Please help me out.

## Your Environment
 I'm using laravel 5.5.

**Comment by sandervanhooft** [comment]
Hi @rassemdev ,

It seems there is no payment method enabled in your account (or the specific method field you're passing is not enabled). Please check your Mollie dashboard.

This is not an issue with `laravel-mollie`, so for follow up please contact [Mollie support](http://mollie.com/support).

**Comment by rassemdev** [comment]
Can't i just use it for test environment!

**Comment by flymke** [comment]
I had the same issue. I created a new mollie tes api key and changed that in my application --> that seemed to solve the issue. Not sure if this counts to anybody but might be worth a try. ✌️

**Comment by jasperf** [comment]
Just had a similar error as well:

```
Mollie\Api\Exceptions\ApiExceptionPOST /dashboard/subscription/pay
[2022-02-15T03:26:34+0100] Error executing API call (422: Unprocessable Entity): No suitable payment methods found. Documentation: https://docs.mollie.com/overview/handling-errors
Linked event: 4 minutes ago · Feb 15th, 09:26:34 GMT+7
Default grouping
P
|
unhandled
Mollie\Api\Exceptions\ApiException · [2022-02-15T03:26:34+0100] Error executing API call (422: Unprocessable Entity): No suitable payment methods found. Documentation: https://docs.mollie.com/overview/handling-errors
app/Services/PaymentService.php:37 App\Services\PaymentService::createPayment	
            'sequenceType' => $options['sequenceType'],
            'description' => $options['description'],
            'webhookUrl' => route('webhooks.mollie'),
            'redirectUrl' => data_get($options, 'redirectUrl'),
        ]);
        return $payment;
app/Http/Controllers/Dashboard/SubscriptionController.php:202 App\Http\Controllers\Dashboard\SubscriptionController::pay
```

 Then I checked payment methods following https://help.mollie.com/hc/en-us/articles/115000648269-How-do-I-activate-payment-methods-in-my-account- and saw all methods were set to evulating. Just thought to leave this here for others with a similar issues.

**Comment by sannegrafistore** [comment]
I have the same issue.
Live key returns this error. Test key works fine.
5 payments methods are active.

Also switched live key with another website profiel (woocommerce) that works. Still the same error occurs with laravel mollie.

What am I missing here?

**Comment by brandosius** [comment]
I have the same issue... Testkey works great, live gives me this errors..

**Comment by Naoray** [comment]
Hi @brandosius,

Please ensure you’ve completed the onboarding process on the Mollie dashboard to use the live key and execute payments.

**Comment by brandosius** [comment]
> Hi @brandosius,
> 
> Please ensure you’ve completed the onboarding process on the Mollie dashboard to use the live key and execute payments.

Yes, I did, but there was a SEPA issue. Now it's right. So if you have this error, check if the SEPA is on in the backend.

**Comment by Naoray** [comment]
I don’t really understand what you are saying with this.
