### ISSUE TITLE
Not redirecting to payment page.

### ISSUE THREAD

**Issue by rassemdev** [mollie/laravel-mollie#97]
I'm trying to integrate laravel-mollie in my e-commerce website and followed your example to implement it. When i'm creating new payment in should redirect me to payment page, But its not showing anything.. here is my code:

`     public function preparePayment($data, $orderId)
      {
	    $payment = Mollie::api()->payments()->create([
		   'amount' => [
                         'currency' => 'EUR',
				    'value' => '100.00',
			    ],
			    "description" => "My first API payment",
			    "redirectUrl" => route('mollie.payment.status'),
			    'webhookUrl' => route('webhooks.mollie'),
			    "metadata" => [
				    "order_id" => $orderId,
			    ],
		    ]);

		$payment = Mollie::api()->payments()->get($payment->id);

		// redirect customer to Mollie checkout page
		return redirect($payment->getCheckoutUrl(), 303);
	}`

I printed the url. which is showing the link. But not redirecting to the payment page. What did i do wrong! can anyone point me out?

**Comment by ndijkstra** [comment]
Hi @rassemdev,

Can you try it without this part `$payment = Mollie::api()->payments()->get($payment->id);`?

**Comment by rassemdev** [comment]
@ndijkstra no use... same.

**Comment by ndijkstra** [comment]
Is it possible that an exception is thrown?

**Comment by rassemdev** [comment]
ahh. sorry.. my fault.. got it.. I using using trait to use it..
