### ISSUE TITLE
Mollie connect locale

### ISSUE THREAD

**Issue by sweebee** [mollie/laravel-mollie#98]
When using mollie connect to connect to a Mollie account, you get redirected to https://www.mollie.com/dashboard/signup?lang=en

is there a way to change the locale to ```nl```?

**Comment by sandervanhooft** [comment]
Good question @sweebee , I'll look into this.

**Comment by sandervanhooft** [comment]
@sweebee what method are you calling specifically when this occurs?

**Comment by sweebee** [comment]
I'm calling the oauth login method:

```
return Socialite::with('mollie')
		                     ->scopes(['...'])
		                     ->redirect();
```

**Comment by sandervanhooft** [comment]
Have you tried this?

https://laravel.com/docs/5.8/socialite#optional-parameters

**Comment by sandervanhooft** [comment]
Closing this issue, let me know if the problem persists.

**Comment by PieterCappelle** [comment]
You fix this with the following code:
```
        return Socialite::with('mollie')
            ->with([
                'locale' => 'nl',
            ])
            ->scopes([
                'profiles.read',
                'onboarding.read',
                'onboarding.write',
                'organizations.read',
                'organizations.write'
            ])
            ->redirect();
```
